### ISSUE TITLE
QupZilla File Chooser Broken

### ISSUE THREAD

**Issue by RolandHughes** [KaOSx/apps#100]
#### Submission type

  - [ x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> qupzilla 2.0.91-1

#### Used repositories

> standard

#### Expected behaviour

> expected chosen file to be returned to dialog

#### Actual behaviour

> nothing

#### Steps to reproduce the problem

> Install both FireFox and Opera from the repos along side QupZilla.
Visit the following, or pretty much any Indeed.com link without being logged in at Indeed.com

https://www.indeed.com/viewjob?jk=0506c8d89fd4829e&q=title%3A(technical+writer)&tk=1b7sr9tff05kg2l6&from=ja&alid=57b33f1be4b094d4802017fd&utm_source=jobseeker_emails&utm_medium=email&utm_campaign=job_alerts

Click on Apply button at bottom to bring up dialog. Click on browse button to add resume then choose any supported file type and click "open."

In QupZilla the file name is not returned. In both Opera and Firefox the file name is returned as expected.

#### System info link created by Octopi > Tools > SysInfo

> https://gist.github.com/479366e53afe409685f93aac60905e0e

**Comment by demmm** [comment]
Post the output of
```
pacman -Qi boinctui
```

**Comment by RolandHughes** [comment]
[roland@i7-desktop boinc]$ pacman -Qi boinctui
Name            : boinctui
Version         : 2.4.4-1
Description     : Curses based fullscreen BOINC manager
Architecture    : x86_64
URL             : https://sourceforge.net/projects/boinctui/
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : expat  gcc-libs  openssl
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 216.00 KiB
Packager        : Unknown Packager
Build Date      : Sat 21 Jan 2017 07:28:29 PM CST
Install Date    : Sat 21 Jan 2017 07:29:04 PM CST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None

**Comment by demmm** [comment]
I see the same behavior now in Chrome, Firefox and any Qtwebengine based browser (Qupzilla included).
File dialog opens, select an html file for example, upload completes, Indeed.com shows a new dialog to provide email address and "Next" button.  There is no difference in Qupzilla compared to any other browser.
You still see a different Qupzilla behavior?

**Comment by RolandHughes** [comment]
Sorry, I had 2 new books to get out along with a Web site for the first book.  
http://lesedi.us/
Had to bail on KaOS when it didn't have support for American English, only UK English. First book and site are done. Next book is another for this series: http://theminimumyouneedtoknow.com/

Once that is completed I can look into KaOS again.

**Comment by demmm** [comment]
Issue cannot be reproduced, reporter no longer uses KaOS, closing.
