### ISSUE TITLE
Libre Office Writer spellcheck broken - not setting language for documents

### ISSUE THREAD

**Issue by RolandHughes** [KaOSx/apps#101]
#### Submission type

  - [x ] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> libreoffice 5.3.0.3-1

#### Used repositories

> standard

#### Expected behaviour

> Typing the following text then hitting F7 to spell check should have flagged quite a few errors and offered suggested alternative spellings.

The farte in the winde waz quite commic.

#### Actual behaviour

> Spelling errors not detected because language is not correctly set.

#### Steps to reproduce the problem

> Install KaOS choosing Chicago, IL as location so all things get set up for proper English
Install LibreOffice and FocusWriter from repo

This step optional: Remove the incorrect English dictionary which gets installed by default and hand build/install hunspell-en-us-large from the AUR so you have a proper English dictionary.

Open new FocusWriter document, type "The farte in the winde waz quite commic." Hit the F7 key to invoke spell check and notice how everything works.

Open new LibreOffice Writer document and type "The farte in the winde waz quite commic." then hit F7 to invoke spell check. Notice how nothing works.

#### System info link created by Octopi > Tools > SysInfo

> https://gist.github.com/d4975579e6eea7fbac6a2d65e27fcd09
![lo_busted_1](https://cloud.githubusercontent.com/assets/1883220/22619195/f1b18f54-eab4-11e6-8299-2513d8c9e003.png)
![lo_busted_2](https://cloud.githubusercontent.com/assets/1883220/22619196/f1b5321c-eab4-11e6-9653-8aa96ec8b32a.png)
![lo_busted_3](https://cloud.githubusercontent.com/assets/1883220/22619197/f1c0ed64-eab4-11e6-8040-aaa1760fca73.png)

**Comment by demmm** [comment]
Default install does not come with hunspell for your locale.  There is no issue with focuswriter or libreoffice spellcheck (F7) when installing the correct hunspell for your location.  In this case, add hunspell-en to your install.

**Comment by RolandHughes** [comment]
hunspell-en is incorrect for my location. That is British English not American English.
We spell catalog they catalogue. We say eraser they say rubber.

**Comment by demmm** [comment]
hunspell-en has spell check for all English locations, including GB, US, NZ and so on.  Make sure to set to desired locale.

**Comment by RolandHughes** [comment]
It did NOT work. Other distros have different hunspell package for EN-US because mashing them together never works. Even Arch has a US EN package. I tried that one for a while but just couldn't risk it.

**Comment by demmm** [comment]
That another distro builds from the same source, then splits on packaging does not make EN US a different package.  Please compare the sources and builds used, you will note they are the same.  Just EN AU is not included in KaOS.

**Comment by RolandHughes** [comment]
All I know is with the locale correctly set to where I live in the United States, it was giving me UK spellings. Moot point now though. Work required a stable tool and I couldn't ever get a stable snap of KaOS to lock down for work.

**Comment by demmm** [comment]
And you state all works correctly when you use the same sources in another distro?  Or you had the same issues, unless you installed EN US large?
That can be fixed, see the README for the differences between the 2 (scroll down to the bottom/readme section:
https://sourceforge.net/projects/wordlist/files/speller/2017.01.22/

**Comment by RolandHughes** [comment]
Only large worked.
I'm sorry, I spent too much time hacking trying to get a reasonably stable KaOS desktop to work with. Had to bail. Need to both eat and live indoors.

**Comment by demmm** [comment]
So it is correctly closed then, as your first image shows, you did not have any spell checking installed, log shows only for about 10 minutes on January 20 did you you have hunspell-en.  After that and at the time of this bug report, no KaOS hunspell-en packages used.
With KaOS hunspell-en installed and default (US) settings:
![](http://wstaw.org/m/2017/03/09/Screenshot_20170309_171906.png)

**Comment by RolandHughes** [comment]
I guess it depends on what you consider a bug. 

Personally I would consider it a distro bug to install a word processor and not install the dictionary as a dependency when one exists.

Personally I would also consider it a distro bug when the EN dictionary throws up UK spellings in America.

But that is me.

I wish you well with the distro. Hopefully at some point you will get a stable, usable world and archive it off as either an LTS or a non-rolling version so users can enjoy the distro without having to hand jam everything. Be hard to get actual donors, at least significant donors, without doing something like that.
