### ISSUE TITLE
jitsi won't launch because java can't be found

### ISSUE THREAD

**Issue by keijukainen** [KaOSx/apps#102]
#### Submission type

* Bug report

#### Package name & version you are having issues with or have a request for

jitsi 2.8.5426-2

#### Used repositories

KaOSx/apps

#### Actual behaviour

Clicking launcher from application menu (jitsi.desktop) or launching from command line results in the error below:

/usr/bin/jitsi: line 17: /bin/java: No such file or directory

The jitsi bash script contains a reference to $JAVA_HOME/bin/java but $JAVA_HOME variable isn't defined so the script thinks we want it to look in /bin instead of /usr/bin.

/usr/bin/java -> /usr/lib/jvm/java-8-openjdk/bin/java

#### Steps to reproduce the problem

Install jitsi. Run jitsi from konsole.

#### System info link created by Octopi > Tools > SysInfo

https://gist.github.com/ba4f6d26a2d53d5b23e6e6d7f51b5103

**Comment by demmm** [comment]
Have you made it work?  Adjusted the script or the .desktop file to adjust for java 8?  If so then please post your used settings.

**Comment by keijukainen** [comment]
I didn't have java on my system prior to installing jitsi.  So when I installed jitsi with pacman it automatically downloaded and installed the openjdk package.  Apparently the $JAVA_HOME variable does not get set until you restart.  So when I first attempted to run the program it couldn't find java.  I now have it working.  I think a safer way of executing the bash script would be to test for an empty variable and then test if it points to a valid folder.  If not, set the JAVA_HOME variable.

`if [ -z "$JAVA_HOME" ] || [ ! -e "$JAVA_HOME" ]; then`
`   export JAVA_HOME="/usr/lib/jvm/java-8-openjdk"`
`fi`
`COMMAND=("$JAVA_HOME/bin/java"....`

**Comment by demmm** [comment]
A needed restart is logic for newly installing JAVA/JDK, if that is what you missed, then no change will be needed for this package.
Closing the issue as is now.
Reopen if you can duplicate this issue after a restart and newly installed openjdk.
