### ISSUE TITLE
filezilla.desktop doesn't show in the menu

### ISSUE THREAD

**Issue by fjmorazan** [KaOSx/apps#103]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> filezilla  3.24.1-1 

#### Used repositories

> build

#### Expected behaviour

> filezilla app appears in the menu

#### Actual behaviour

> the .desktop file doesn't show

#### Steps to reproduce the problem

> non-printable character on the header of filezilla.desktop makes update-desktop-database
throws an error message:'"Could not parse file "/usr/share/applications/filezilla.desktop": Key file contains line '?[Desktop Entry]' which is not a key-value pair, group, or comment'  and make it unable to show the app in the menu

#### System info link created by Octopi > Tools > SysInfo

> https://gist.github.com/4629b0e2a3117664d4c4f40b94d072d0

**Comment by demmm** [comment]
This is an upstream issue, something went wrong in this commit:
https://svn.filezilla-project.org/filezilla/FileZilla3/branches/3.24.x/data/filezilla.desktop?r1=8205&r2=8206
The patch shows the faulty character added in that commit (line 1)
https://svn.filezilla-project.org/filezilla/FileZilla3/branches/3.24.x/data/filezilla.desktop?r1=8205&r2=8206&view=patch
For now will revert this patch in KaOS for filezilla 3.24.1
