### ISSUE TITLE
KMyMoney: error opening shared library kmymoney: libKF5Gpgmepp.so.5

### ISSUE THREAD

**Issue by padhia** [KaOSx/apps#104]
#### Submission type

  - [X] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> kmymoney-4.100.8

#### Used repositories

> core, main, apps

#### Expected behaviour

> Application should not fail to start

#### Actual behaviour

> Application fails to start with following message display on the terminal:
`kmymoney: error while loading shared libraries: libKF5Gpgmepp.so.5: cannot open shared object file: No such file or directory`

#### Steps to reproduce the problem

> start kmymoney from terminal to display the above error message

#### System info link created by Octopi > Tools > SysInfo

> https://gist.github.com/6d81d002bb51043a165ebc456b9a26f8

**Comment by demmm** [comment]
Can't reproduce, kmymoney was build on new ways of gpgme, starts correct, ldd output:
```
$ ldd /usr/bin/kmymoney | grep gmepp
        libgpgmepp.so.6 => /usr/lib/libgpgmepp.so.6 (0x00007fd8c89df000)
```
```
$ pacman -Qi kmymoney
Name            : kmymoney
Version         : 4.100.8-1
Description     : An finance manager for KDE with HBCI support
Architecture    : x86_64
URL             : http://www.kmymoney.org/
Licenses        : GPL
Groups          : office
Provides        : None
Depends On      : kcoreaddons  kconfig  ki18n  khtml  kdelibs4support  kcompletion  kcmutils  kitemviews  kservice  kwallet  kholidays  gpgme
                  kcontacts  akonadi-contacts  akonadi  kidentitymanagement  kross  shared-mime-info  boost-libs  pulseaudio  libofx  libical
                  alkimia  kdiagram  kactivities  aqbanking
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : kf5-kmymoney
Replaces        : kf5-kmymoney
Installed Size  : 22.70 MiB
Packager        : Anke Boersma <demm@kaosx.us>
Build Date      : Fri 25 Nov 2016 12:18:40 PM EST
Install Date    : Fri 25 Nov 2016 12:28:34 PM EST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : SHA-256 Sum
```
Please post your output of pacman -Qi kmymoney

**Comment by padhia** [comment]
This looks strange.

```
~> kmymoney 
kmymoney: error while loading shared libraries: libKF5Gpgmepp.so.5: cannot open shared object file: No such file or directory
~> sudo pacman -Qi kmymoney
error: package 'kmymoney' was not found
~> 
```


I then manually removed `kmymoney` and  reinstalled it from the repo and it opened up without this error. I do remember having compiled `kmymoney` myself to a specific commit to overcome some bugs. My guess is, I must have had some leftover `kmymoney` from then.

Thanks for looking into this and sorry for the trouble.
