### ISSUE TITLE
Ghosted / Scrambled GUI

### ISSUE THREAD

**Issue by konoerik** [KaOSx/apps#105]
#### Submission type

  - [ x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> …Desktop Environment w/ Nouveau

#### Used repositories

> …Standard

#### Expected behaviour

> …Smooth and clean transitions when typing or selecting items from menus

#### Actual behaviour

> …Ghosting effect and scrambled fonts when using system menus, typing on Konsole, selecting text. See image below for example. It happens consistently on all menu items for applications also.
![spectacle cj2291](https://cloud.githubusercontent.com/assets/4625814/23585784/20152912-0155-11e7-98c5-6a31bc021819.png)

#### Steps to reproduce the problem

> …No additional steps; Fresh installation of 2017.02 image (issue persists after system update also).

#### System info link created by Octopi > Tools > SysInfo

> …https://gist.github.com/anonymous/1bbb83c64dee1186ae22db20b5b79a61

**Comment by demmm** [comment]
Since there are many nouveau issues listed in your journalctl log, please try with non-free nvidia or try to use the in-kernel modestting driver, for non-free:
https://kaosx.us/docs/nvidia/
For modesetting, remove nouveau:
```
sudo pacman -R xf86-video-nouveau
```
and reboot

Best try non-free first though.

**Comment by konoerik** [comment]
Thanks @demmm!

I reinstalled with nouveau and followed the instructions on the link you shared to replace with non-free and it works well now. 
This is the new sys info: https://gist.github.com/anonymous/76eaa2bb4385d434aa67e505b114ccbf

To give some background:
1. The very first KaOS installation (a few days ago) was with non-free drivers and went through fine, but the system would hang very often - moving the panel was a sure way to get it to hang. 
Since then every attempt to re-install with non-free drivers has caused the system to hang at 22%-23% of installation; the screen freezes and mouse pointer recovers after 1-2 minutes but the rest of the DE remains frozen.
2. I tried installing with free drivers and noticed the behavior described in this bug
3. I have also tried installing with the integrated card alone (Intel HD530) by physically removing the Nvidia GPU - system constantly crashes and powers down during installation also at 22%-23%

**Comment by demmm** [comment]
Sorry, I missed from the first gists that this was a hybrid system, that one only listed the nvidia card.
That would explain the system malfunctioning when using non-free, since you need the different packaged libgl for hybrid.
Make sure to also check [hybrid graphics](https://kaosx.us/docs/hybrid_gfx/) if you do decide to enable the integrated card again.
For the Intel HD530 only install crashes I will need to see logs to be able to figure how to fix that.

System hang at 22-23% means all is complete unresponsive or means the install hangs?  If the latter, how long did it stay at 23%?  It does take some time to copy the full ISO to the target.....

**Comment by konoerik** [comment]
I'm not sure if this qualifies as a hybrid system, since it is a desktop PC; the BIOS does not initialize the Integrated GPU when there is a discrete one available (this is the default option anyway), that's why is missing from the logs probably.

For the installation issues there are two behaviors:
1. In the case of using non-free nvidia drivers, the entire system becomes unresponsive at 23%; I waited about 20min for traffic to stop from installation USB (it has an LED) assuming only the GUI was hang; upon reboot however there was nothing installed.
2. In the case of using Intel HD530 alone, the system powers off suddenly at 23%

Both behaviors were repeated multiple times.

**Comment by demmm** [comment]
Is there any way you can SSH into the system when the hang occurs, see if the logs can give an indication what is going on?
Have you tried to have htop open, see if it uses up all RAM? 
Plus I have to ask with this, how was the install media created?  md5sum checked?  Tried another USB/DVD?  Probably not a media issue, but need to look at the simple options too.

**Comment by konoerik** [comment]
I can try to SSH and check htop also. What logs specifically would be helpful?

I used 'dd' to copy the ISO on the USB. Just checked md5sum also:
ISO: a9533c7a0ec43f1be5303a6ab8dedf43
USB: a9533c7a0ec43f1be5303a6ab8dedf43

**Comment by demmm** [comment]
As expected, not a live media issue.

dmesg & journalctl should be able to show what is going on, if htop is not already showing RAM is getting exhausted.

**Comment by konoerik** [comment]
I should've paid closer attention to the initial log after all. It points to high CPU temperature, which explains the sudden crashes. The cooler was indeed not clipped in correctly.

As far as this bug goes, the nouveau drivers don't seem to agree with my setup but I am not sure if it is KaOS-specific or KDE-specific either. Haven't used either before.

**Comment by demmm** [comment]
Make sure to test different settings for nouveau, is it just an issue with openGL, needs openGl 3.1 and so on.
systemsettings > display & monitor > compositor, switch rendering backend to  Xrender and/or try to set OpenGl to 3.1.

**Comment by demmm** [comment]
No further response from submitter.
