### ISSUE TITLE
system-config-printer depends on libgnome-keyring

### ISSUE THREAD

**Issue by keijukainen** [KaOSx/apps#106]
#### Submission type

- [x] Bug report

#### Package name & version you are having issues with or have a request for

system-config-printer
1.5.9

#### Actual behaviour

Running system-config-printer from console results in the following:

`Traceback (most recent call last):
  File "/usr/share/system-config-printer/system-config-printer.py", line 84, in <module>
    import jobviewer
  File "/usr/share/system-config-printer/jobviewer.py", line 57, in <module>
    gi.require_version('GnomeKeyring', '1.0')
  File "/usr/lib/python3.5/site-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GnomeKeyring not available`

After I installed libgnome-keyring it worked fine. That package needs to be added as a dependency for system-config-printer. Thanks!

**Comment by demmm** [comment]
libgnome-keyring is long unmaintained and depreciated, so won't be added to any as a new depend.  I'll figure a patch so it will compile  with `USE_KEYRING=False`
