### ISSUE TITLE
Can't launch Godot Engine without a .cfg file

### ISSUE THREAD

**Issue by EQLucky** [KaOSx/apps#107]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> godot 2.1.2-1

#### Used repositories

> stable

#### Expected behaviour

> When I launch the app, it should show the Project Manager window.

#### Actual behaviour

> It just doesn't launch. When you try to execute it from the terminal, it says "error: Couldn't load game path '.' " ...followed with the --help option text.

[http://i.imgur.com/yrpkFFG.png](url)

#### Steps to reproduce the problem

> Launch Godot normally.

#### System info link created by Octopi > Tools > SysInfo

> https://gist.github.com/2675a6d7c7b8c573a020544c3309c124

**Comment by demmm** [comment]
Make sure to read the full output you get, it shows how to proper use godot.
Example of using godot, install minilens and then run godot with the proper parameters:
```
godot -path /opt/minilens
```
This is not a bug, but needing to proper follow instructions for this game engine, see upstream docs.

**Comment by demmm** [comment]
The tools option is added, since it seems you want to use the project-manager part, rebuild is up:
```
sudo pacman -U http://kaosx.tk/repo/build/godot-2.1.2-2-x86_64.pkg.tar.xz
```
See if that adds what you are looking for and sorry for misunderstanding the report.

**Comment by EQLucky** [comment]
Thank you so much, demm. I've upgraded the package and now it shows the project manager when you launch it. 
Cheers!
