### ISSUE TITLE
dependency is broken in krdc

### ISSUE THREAD

**Issue by ericklzr** [KaOSx/apps#11]
Krdc uses freerdp now and no more rdesktop.
![erro-krdc](https://cloud.githubusercontent.com/assets/8203786/3630387/d3a36e76-0eaa-11e4-9282-f6cc49e8aff3.png)

**Comment by demmm** [comment]
krdc 14.12.1 had an upstream fix for this.
Please report back if working correctly now.

**Comment by demmm** [comment]
No further response from submitter
