### ISSUE TITLE
Umbrello error

### ISSUE THREAD

**Issue by alexmigf** [KaOSx/apps#111]
Submission type

  - [ X ] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> Umbrello 17.03.90-1

#### Expected behaviour

> Open app

#### Actual behaviour

> Error: Cannot load library libkdeinit5_umbrello: (libkdeinit5_umbrello: cannot open shared object file: No such file or directory)

#### Steps to reproduce the problem

> Created a new standard user but the problem persist there.

#### System info link created by Octopi > Tools > SysInfo

> https://gist.github.com/a9ee1e6482c9a4efbbca28d7a2b97410

**Comment by demmm** [comment]
The journal shows many errors regarding kinit, plasma, kactivities, none seen on regular systems.
Did you ever update and lost power during the update?  Ever used force with pacman?

What is the complete output when starting umbrello from cli?  Run with:
```
umbrello5
```
and post all the output including that command.

**Comment by alexmigf** [comment]
I just do package updates throw pacman and never lost power during updates. I think i never used force but i can't confirm with 100% sure.

https://pastebin.com/e41QxT0A

**Comment by demmm** [comment]
I do not see any errors in that pastebin.  Does it still not run?

**Comment by alexmigf** [comment]
It runs with that command, i can confirm. But from start menu no.

**Comment by demmm** [comment]
Good, this means an upstream bug.
Seems they changed the binary from umbrell to umbrello5 but did not adjust the .desktop.
Edit /usr/share/applications/org.kde.umbrello5.desktop and add the 5 to the exec line so it reads
```
Exec=umbrello5 %u -qwindowtitle %c
```
If that fixes your issue, open an upstream bug report.
Fix will be packaged in KaOS as a temp solution.

**Comment by alexmigf** [comment]
Ok, good, i will do it.

Thank you!

**Comment by demmm** [comment]
Here is the commit that sets it to umbrello5, as you see, forgotten to adjust .desktop in this commit:
https://cgit.kde.org/umbrello.git/commit/?id=0d1832c4cf7f070e212d25bccf7162d989dac0a7
