### ISSUE TITLE
Sound (control) disappears through relogin

### ISSUE THREAD

**Issue by ShalokShalom** [KaOSx/apps#112]
#### Submission type

  - [x] Bug report

#### Package name & version you are having issues with or have a request for

> … Pulseaudio or ALSA

#### Used repositories

> … core, main, apps

#### Expected behaviour

> … Sounds runs, plasma-pa is working, Multimedia KCM show devices

#### Actual behaviour

> … Sound fails to play at all, sometimes work the sound, while i cant control it 
In both cases are all sound devices in my Multimedia KCM disappeared.

#### Steps to reproduce the problem

> … Log out, relogin

#### System info link created by Octopi > Tools > SysInfo

> … Error: "\xE2" on US-ASCII (Output, which i get when i run SysInfo)

![screenshot_20170414_085718](https://cloud.githubusercontent.com/assets/6344099/25035922/f02f983e-20f0-11e7-9688-13cae4439f45.png)

**Comment by demmm** [comment]
When this happens, can you run:
```
start-pulseaudio-x11
```
and post if then all returns without restarting

**Comment by demmm** [comment]
This is an issue in pulseaudio, fails to start on login.  To make it work, make sure it does not load module-esound-protocol.  Not sure yet when this issue started.  Do you know if this was working correctly before the middle of January?  That is when pulseaudio 10.0 came in the repo.
To check if the fix works for you:
```
kdesu kate /etc/pulse/default.pa
```
and comment out 3 lines:
.ifexists module-esound-protocol-unix.so
load-module module-esound-protocol-unix
.endif
```
(place ## in front of those or remove)

**Comment by Seeder101** [comment]
I can confirm this issue the sound applet in the system tray get no sound cards or devices at all 
I have to restart sometimes...but I do get sound from my headphones even tho there's no sound card detected in the applet

**Comment by ShalokShalom** [comment]
Is this issue well known upstream?

**Comment by demmm** [comment]
Please answer questions as posed in my second reply.
Did you actually do any of the editing as asked?

**Comment by ShalokShalom** [comment]
Fix works.

**Comment by demmm** [comment]
Fix is not in the repos, will stay open until packaged & moved to all users.
