### ISSUE TITLE
gis-weather widget failure

### ISSUE THREAD

**Issue by madirishman** [KaOSx/apps#115]
#### Submission type

  - [X ] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> gis-weather-git-0.8.2.48-1-x86_64

#### Used repositories

> Default

#### Expected behaviour

> Both Widget and Indicator display
#### Actual behaviour

> Indicator displays, widget does not. Both displayed after installation and then the widget stopped displaying.

#### Steps to reproduce the problem

> Launch gis-weather…

#### System info link created by Octopi > Tools > SysInfo

> Using a different System can't provide

**Comment by demmm** [comment]
There is no gis-weather-git in KaOS repositories.
