### ISSUE TITLE
Error Qgit

### ISSUE THREAD

**Issue by madirishman** [KaOSx/apps#116]
#### Submission type

  - [X ] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> qgit 2.7-1

#### Used repositories

> core, main, and apps

#### Expected behaviour

> Launch without error

#### Actual behaviour

> An error occurred while executing git --version. Git says unable to start the process

#### Steps to reproduce the problem. 
> Launch qgit

#### System info link created by Octopi > Tools > SysInfo

> https://gist.github.com/anonymous/4b04e75161a1129c8b56e6f7193962f3

**Comment by demmm** [comment]
Do you have git setup?  Qgit is just a GUI for working with git, does not set it up for you
And post the output of pacman -Qi glabels

**Comment by madirishman** [comment]
I didn't. I do now. THat was the issue. I'll close the Bug. I emailed you the output of pacman -Qi glabels.

**Comment by madirishman** [comment]
Installing git solved the issue.

**Comment by demmm** [comment]
Then this is a bug, missing depend for QGis, rebuild will be up shortly.
