### ISSUE TITLE
QBittorrent - libboost_system.so.1.62

### ISSUE THREAD

**Issue by ShalokShalom** [KaOSx/apps#117]
#### Submission type

  - [x] Bug report

#### Package name & version you are having issues with or have a request for

> … qbittorrent 3.3.12-3

#### Used repositories

> … core, main, apps

#### Expected behaviour

> … runs

#### Actual behaviour

> … qbittorrent: error while loading shared libraries: libboost_system.so.1.62.0: cannot open shared object file: No such file or directory

#### Steps to reproduce the problem

> … start qbittorrent

#### System info link created by Octopi > Tools > SysInfo

> … SysInfo is broken here

**Comment by demmm** [comment]
Is your system fully up to date?  Show output of:
```
pacman -Qi qbittorrent
```
and:
```
ldd /usr/bin/qbittorrent | grep boost
```
Qbittorrent was rebuild for boost 1.63.0 and links correctly, see output here:
```
$ ldd /usr/bin/qbittorrent | grep boost
        libboost_system.so.1.63.0 => /usr/lib/libboost_system.so.1.63.0 (0x00007f8353c71000)
        libboost_chrono.so.1.63.0 => /usr/lib/../lib/libboost_chrono.so.1.63.0 (0x00007f83512f4000)
        libboost_random.so.1.63.0 => /usr/lib/../lib/libboost_random.so.1.63.0 (0x00007f83510ed000)
```
Show your pacman.log from the last 2 weeks.

**Comment by ShalokShalom** [comment]
pacman -Qi qbittorrent: https://gist.github.com/ShalokShalom/c29dbdb124fca94ee68fc38c4f04f3e5
ldd: https://gist.github.com/ShalokShalom/0809c26ca08b1a7fe2a5ebd65d731898
pacman.log: https://gist.github.com/ShalokShalom/a249e2a2964d3c731cddc1ad8d887bdc
Here is SysInfo: https://gist.github.com/anonymous/ac57efc210faafd79a6fc76e0d949086

**Comment by demmm** [comment]
Issue with user database, wrong libtorrent-rasterbar version installed.
