### ISSUE TITLE
SysInfo - Error: "\xE2" on US-ASCII 

### ISSUE THREAD

**Issue by ShalokShalom** [KaOSx/apps#118]
#### Submission type

  - [x] Bug report

#### Package name & version you are having issues with or have a request for

> … Octopi 0.8.106-1

#### Used repositories

> … core, main, apps

#### Expected behaviour

> … SysInfo URL appears

#### Actual behaviour

> … Error: "\xE2" on US-ASCII 

#### Steps to reproduce the problem

> … Octopi > Tools > SysInfo

#### System info link created by Octopi > Tools > SysInfo

> … ;)

**Comment by demmm** [comment]
This means you have a non-ascii character in your pacman.log (German umlaut?)

Move current log
```
cp /var/log/pacman.log ~/Documents/pacman.log
``` 
Delete original:
```
sudo rm /var/log/pacman.log
```
and try SysInfo again.

**Comment by ShalokShalom** [comment]
![screenshot_20170515_144838](https://cloud.githubusercontent.com/assets/6344099/26058306/9998ccf2-397d-11e7-8195-da628e41a20e.png)

**Comment by demmm** [comment]
One of the other logs has a non-ascii character, move the installation.log the same way

**Comment by ShalokShalom** [comment]
http://stackoverflow.com/a/42366333

**Comment by ShalokShalom** [comment]
Yep, installation.log caused it. Can you prevent this to reappear?

**Comment by ShalokShalom** [comment]
https://gist.github.com/ShalokShalom/f69009901ae68e63bbb1f34fb1c5dbe4

**Comment by demmm** [comment]
Maybe aarnt can adjust Ocopi for this, otherwise it needs adjusting in Calamares for German output.
