### ISSUE TITLE
Menu not showing correctly

### ISSUE THREAD

**Issue by pascalhcm** [KaOSx/apps#120]
#### Submission type

  - [X ] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

menu is not correctly drawn when clicking on items or moving over, missing the borders it seems

KDE plasma : 5.10.1
KDE frameworks : 5.35.0
Qt : 5.9.0
kernel : 4.10.9-1

#### Used repositories

standard

#### Expected behaviour

whole menu as before the last big update 

#### Actual behaviour

drawing of the menus are incomplete
![screenshot_20170615_194713](https://user-images.githubusercontent.com/29457072/27181971-f1390334-5203-11e7-8395-2061fdf4f246.png)
![screenshot_20170615_195207](https://user-images.githubusercontent.com/29457072/27182045-29e1d0bc-5204-11e7-8ba6-dd8d8fc0a493.png)

#### Steps to reproduce the problem

none, it is automatic when start computer

#### System info link created by Octopi > Tools > SysInfo

https://gist.github.com/551530110b9d4e22c9144b4098cf18b4

**Comment by demmm** [comment]
Almost your complete install (980 packages) do not belong to the pacman database.  Where are you installing from?  Are you using force?
Until you can get a clean `pacman -Qm` output, nothing much can be done with this bug report.

**Comment by pascalhcm** [comment]
I installed Kaos with iso 2017.02, then use the repositories installed together, no extras/changes except for : some app from kcp (now deleted, pacman -Qm output is clean) and flatpak (skype), no installation with - force
after today update (65 packages) and cleaning pacman -Qm the problem remains the same, no borders when showing menus

**Comment by demmm** [comment]
The SysInfo showed all that already (install date and so on).
But no idea how you can clear almost 1000 packages that showed in pacman -Qm and still have an install left.
Make sure to show logs of what you are doing (full pacman output of last updated, full pacman output of how you "cleaned" pacman -Qm results), bug reports without logs are useless.

**Comment by pascalhcm** [comment]
i had only 3 packages showing with pacman -Qm : minidlna / kfoldersync / cyrus-sasl and i just uninstalled them with Octopi , now the Qm pacman output is totally empty
here is pacman.log
[pacman.log.txt](https://github.com/KaOSx/apps/files/1079668/pacman.log.txt)
sorry if i miss to send relevant info as it is the first time ever i'm opening a bug report...

**Comment by demmm** [comment]
If pacman -Qm is now resolved and your install belongs to the pacman database again, then see if you can reproduce your issue with a clean, new user.

**Comment by pascalhcm** [comment]
done, and it is all correct, i transfered all datas to the new user, so it is back to normal..
Thanks!

**Comment by demmm** [comment]
You can still use the old user, just need to figure which files in ~/.config got corrupted, but that takes a lot of time
Quick way is not be logged in as that user, rename ~/.config to something like ~/.config_old, login, let the system create a new .config, and then re-use parts of the old carefully.
