### ISSUE TITLE
Filezilla doesn't run

### ISSUE THREAD

**Issue by alexmigf** [KaOSx/apps#122]
#### Submission type

  - [ X ] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> Filezilla

#### Used repositories

> …

#### Expected behaviour

> Open

#### Actual behaviour

> Doesn't open

#### Steps to reproduce the problem

> …

#### System info link created by Octopi > Tools > SysInfo

```
Reading locale option from /home/alexandre/.config/filezilla/filezilla.xml
Fatal Error: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1009,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1010,wx containers,compatible with 2.8).
Aborted (core dumped)
```

**Comment by demmm** [comment]
Seem wxgtk is overly strict on C++ ABI.....
New wxgtk is up (build on GCC6):
```
sudo pacman -U http://kaosx.tk/repo/build/wxgtk-3.0.3.1-1-x86_64.pkg.tar.xz
```
fixes the issue here, please report back if it fixes for you too, if so it will move to all uses quickly

**Comment by alexmigf** [comment]
Yes, it fix the issue.

**Comment by demmm** [comment]
Issue will be closed once wxgtk has moved to the [main] repo.

**Comment by demmm** [comment]
wxgtk is now in main, closing.
