### ISSUE TITLE
telepathy

### ISSUE THREAD

**Issue by ki00** [KaOSx/apps#123]
#### Submission type

I can add a google account, however, 

when I try to add a twitter account it does not do anything, 

when I click on yahoo messenger account it pops:
This IM Account cannot be created - a Telepathy Connection Manager named 'haze' is missing or it cannot handle protocol 'yahoo'. Please try installing haze with your package manager.

when I click on telegram account it pops:
This IM Account cannot be created - a Telepathy Connection Manager named 'morse' is missing or it cannot handle protocol 'telegram'. Please try installing morse with your package manager.

for skype:
This IM Account cannot be created - a Telepathy Connection Manager named 'haze' is missing or it cannot handle protocol 'skypeweb'. Please try installing haze with your package manager.

for ibmsametime:
This IM Account cannot be created - a Telepathy Connection Manager named 'haze' is missing or it cannot handle protocol 'sametime'. Please try installing haze with your package manager.

or sometimes with google:
Ocurrió un error al intentar procesar la petición: Access grant not present

I just need few accounts, but this is what shows or not shows when I click on it

#### Package name & version you are having issues with or have a request for

> …KaOS201706

#### Used repositories

> …updated

#### Expected behaviour

> …Be able to add any account

#### Actual behaviour

> …Do not do anything, or pops up an error message

#### Steps to reproduce the problem

> …Just try to add an account on "mensajería instantánea"

#### System info link created by Octopi > Tools > SysInfo

> …System:    Host: <HOSTNAME> Kernel: 4.10.9-1 x86_64 (64 bit gcc: 5.4.1) Desktop: KDE Plasma 5.10.2 (Qt 5.9.0)
           Distro: KaOS (2017)
Machine:   Device: laptop System: TOSHIBA product: Satellite C45-A v: PSCD2P-014LM2
           Mobo: Type2 - Board Vendor Name1 model: Type2 - Board Product Name1 v: Type2 - Board Version
           UEFI [Legacy]: Insyde v: 1.20 date: 09/18/2013
Battery    BAT1: charge: 12.3 Wh 100.0% condition: 12.3/45.0 Wh (27%)
           model: Panasonic PA5109U-1BRS status: Full
CPU:       Dual core Intel Core i5-3230M (-HT-MCP-) cache: 3072 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 10376
           clock speeds: max: 3200 MHz 1: 2999 MHz 2: 2999 MHz 3: 2999 MHz 4: 2999 MHz
Graphics:  Card: Intel 3rd Gen Core processor Graphics Controller bus-ID: 00:02.0
           Display Server: x11 (X.Org 1.19.3) drivers: intel (unloaded: modesetting,vesa)
           Resolution: 1366x768@60.06hz
           GLX Renderer: Mesa DRI Intel Ivybridge Mobile
           GLX Version: 4.2 Mesa 17.1.2 Direct Rendering: Yes
Audio:     Card Intel 7 Series/C216 Family High Definition Audio Controller
           driver: snd_hda_intel bus-ID: 00:1b.0
           Sound: Advanced Linux Sound Architecture v: k4.10.9-1
Network:   Card-1: Qualcomm Atheros QCA9565 / AR9565 Wireless Network Adapter
           driver: ath9k bus-ID: 02:00.0
           IF: wlp2s0 state: up mac: <filter>
           Card-2: Qualcomm Atheros AR8162 Fast Ethernet driver: alx port: 2000 bus-ID: 03:00.0
           IF: enp3s0 state: down mac: <filter>
Drives:    HDD Total Size: 750.2GB (41.3% used)
           ID-1: /dev/sda model: TOSHIBA_MQ01ABD0 size: 750.2GB
Partition: ID-1: / size: 690G used: 280G (41%) fs: xfs dev: /dev/sda1
           ID-2: swap-1 size: 9.45GB used: 0.00GB (0%) fs: swap dev: /dev/sda2
Sensors:   System Temperatures: cpu: 65.0C mobo: N/A
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 288 Uptime: 1:44 Memory: 4592.6/7881.7MB Init: systemd runlevel: 5 Gcc sys: 6.3.1
           Client: Unknown : octopi inxi: 2.3.17

**Comment by demmm** [comment]
Did you try with adding the optional depend telepathy-haze to your install?

**Comment by demmm** [comment]
Installing haze won't fix this, upstream issue, see:
https://bugs.kde.org/show_bug.cgi?id=364111

**Comment by ShalokShalom** [comment]
@ki00  The upstream Bug report says that installing OpenJDK instead of Java solves this issue: https://gitlab.com/accounts-sso/signon-ui/issues/1#note_94262600

Since KaOS is on OpenJDK exclusively today, is this most likely already solved.
Can you confirm?

**Comment by demmm** [comment]
No further response from submitter, closing.
