### ISSUE TITLE
Bluetooth send file wizard

### ISSUE THREAD

**Issue by ki00** [KaOSx/apps#124]
#### Submission type

  - [ ] Bug report
  - [ ] Feature Request
Just can not send any file through blueotooth with an android phone
It just pop up a message error:

"La conexión con Galaxy Grand Prime ha fallado"

if this error with this phone type has been reported feel free to close it

#### Package name & version you are having issues with or have a request for

> …KaOS 201706

#### Used repositories

> …updated

#### Expected behaviour

> …send files

#### Actual behaviour

> …error, unable to send files

#### Steps to reproduce the problem

> …connect this model through bluetooth, and try to send files

#### System info link created by Octopi > Tools > SysInfo

> ……System: Host: Kernel: 4.10.9-1 x86_64 (64 bit gcc: 5.4.1) Desktop: KDE Plasma 5.10.2 (Qt 5.9.0)
Distro: KaOS (2017)
Machine: Device: laptop System: TOSHIBA product: Satellite C45-A v: PSCD2P-014LM2
Mobo: Type2 - Board Vendor Name1 model: Type2 - Board Product Name1 v: Type2 - Board Version
UEFI [Legacy]: Insyde v: 1.20 date: 09/18/2013
Battery BAT1: charge: 12.3 Wh 100.0% condition: 12.3/45.0 Wh (27%)
model: Panasonic PA5109U-1BRS status: Full
CPU: Dual core Intel Core i5-3230M (-HT-MCP-) cache: 3072 KB
flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 10376
clock speeds: max: 3200 MHz 1: 2999 MHz 2: 2999 MHz 3: 2999 MHz 4: 2999 MHz
Graphics: Card: Intel 3rd Gen Core processor Graphics Controller bus-ID: 00:02.0
Display Server: x11 (X.Org 1.19.3) drivers: intel (unloaded: modesetting,vesa)
Resolution: 1366x768@60.06hz
GLX Renderer: Mesa DRI Intel Ivybridge Mobile
GLX Version: 4.2 Mesa 17.1.2 Direct Rendering: Yes
Audio: Card Intel 7 Series/C216 Family High Definition Audio Controller
driver: snd_hda_intel bus-ID: 00:1b.0
Sound: Advanced Linux Sound Architecture v: k4.10.9-1
Network: Card-1: Qualcomm Atheros QCA9565 / AR9565 Wireless Network Adapter
driver: ath9k bus-ID: 02:00.0
IF: wlp2s0 state: up mac: 
Card-2: Qualcomm Atheros AR8162 Fast Ethernet driver: alx port: 2000 bus-ID: 03:00.0
IF: enp3s0 state: down mac: 
Drives: HDD Total Size: 750.2GB (41.3% used)
ID-1: /dev/sda model: TOSHIBA_MQ01ABD0 size: 750.2GB
Partition: ID-1: / size: 690G used: 280G (41%) fs: xfs dev: /dev/sda1
ID-2: swap-1 size: 9.45GB used: 0.00GB (0%) fs: swap dev: /dev/sda2
Sensors: System Temperatures: cpu: 65.0C mobo: N/A
Fan Speeds (in rpm): cpu: N/A
Info: Processes: 288 Uptime: 1:44 Memory: 4592.6/7881.7MB Init: systemd runlevel: 5 Gcc sys: 6.3.1
Client: Unknown : octopi inxi: 2.3.17

**Comment by demmm** [comment]
No option to test here with bluetooth, but did you try using kdeconnect?
Install it on your android phone, then pair it with your system, works very well for file sharing.

**Comment by ki00** [comment]
the app does not works... at least what I have tried...

**Comment by demmm** [comment]
No needed ans asked for feedback supplied, not reproducible.
