### ISSUE TITLE
Micro - Can't install plugin

### ISSUE THREAD

**Issue by alexmigf** [KaOSx/apps#126]
#### Submission type

  - [ x ] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> Micro

#### Used repositories

> …

#### Expected behaviour

> Install plugin

#### Actual behaviour

> `Error installing filemanager: unable to find a matching  version for "filemanager"`

#### Steps to reproduce the problem

> plugin install filemanager

#### System info link created by Octopi > Tools > SysInfo

> …

**Comment by demmm** [comment]
This is not a bug report.
Not even mentioned what plugin is attempted to be installed.
And how is this a KaOS packaging issue?
Check upstream to find the correct needed requirements.
