### ISSUE TITLE
docker 17.06.0-ce

### ISSUE THREAD

**Issue by devalexandre** [KaOSx/apps#127]
#### Submission type

  - [ x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

Client:
 Version:      unknown-version
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cbb2996c
 Built:        Thu Jun 29 02:43:50 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Thu Jun 29 02:43:30 2017
 OS/Arch:      linux/

> …

#### Used repositories
pacman 
> …

#### Expected behaviour

> …

#### Actual behaviour

> …

#### Steps to reproduce the problem
pacman -S docker
> …

#### System info link created by Octopi > Tools > SysInfo

> …

**Comment by demmm** [comment]
KaOS is not Arch Linux or Arch based, so don't report bugs for that distro here.

**Comment by devalexandre** [comment]
not bug of archlinux, this error in pacman of KAOSX

**Comment by demmm** [comment]
Sorry, but this bug report is still invalid.
No indication what system, no SysInfo provided, I guess one has to guess what provided the output.  No repository `pacman` exists in KaOS.

Please update your system and if you still have an issue with docker, open a proper bug report and provide info asked.
