### ISSUE TITLE
php-xdebug A failure occurred in build

### ISSUE THREAD

**Issue by devalexandre** [KaOSx/apps#129]
#### Submission type

  - [ x  ] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> php-xdebug

#### Used repositories

> kcp

#### Expected behaviour

> …

#### Actual behaviour

> …

#### Steps to reproduce the problem

> kcp  -i php-xdebug

#### System info link created by Octopi > Tools > SysInfo

> https://gist.github.com/d793e3d3936229feaeb1f090808a1a42

**Comment by demmm** [comment]
KCP is not maintained by KaOS, it is users maintained.
It is not in the repositories.
If you have an issue with a KCP package, open an issue there.
http://kaos-community-packages.github.io/
https://github.com/KaOS-Community-Packages
