### ISSUE TITLE
python

### ISSUE THREAD

**Issue by ki00** [KaOSx/apps#130]
#### Submission type

I am posting this here, because the former post was in a wrong thread...
I have done former manual installations of kaos, however, this time it can not be done
as the documentation page, there is 8 MB unformatted space, the main and swap (with former releases and several other distros, it could be done...)
(btw, by default would be better to choose only the gpt table partitioning creation)

#### Package name & version you are having issues with or have a request for

> …2017-07

#### Used repositories

> …2017-07

#### Expected behaviour

> …installation succesful

#### Actual behaviour

> …installation error

#### Steps to reproduce the problem

> …try a manual partition installation

#### System info link created by Octopi > Tools > SysInfo

> …
https://gist.github.com/anonymous/95899f71e9518aafc37ab28eb6003261
https://pastebin.com/keQC92Fi

Error Boost.Python en el proceso "bootldr".
<class 'subprocess.CalledProcessError'>
Comand 'grub-install /dev/sda' returned non-zero exit status 1.
Traceback:
  File "/usr/lib/calamares/modules/bootldr/main.py", line 222, in run
    install_bootloader(boot_loader, fw_type)

  File "/usr/lib/calamares/modules/bootldr/main.py", line 208, in install_bootloader
    check_target_env_call(["grub-install", install_path])

  File "<string>", line 2, in <module>

**Comment by demmm** [comment]
Again, your issue has nothing to do with applications, it is an installation issue:
https://kaosx.us/docs/bugs/
Please read the above (third time linked for you now, and file issues under the correct section. 
https://github.com/KaOSx/calamares/issues

For this fail, it can be answered here, read the instructions given to you when using GPT on ms-dos, you need to set the correct boot flag on the unformatted partition, not an installer issue but user error.  The logs no-where show the needed bios_grub flag is set.

**Comment by ki00** [comment]
ah, ok, I did not tried the flag enabled

**Comment by ki00** [comment]
yes, it is installing nice, without issues,
nice!
