### ISSUE TITLE
kaptan

### ISSUE THREAD

**Issue by ki00** [KaOSx/apps#131]
#### Submission type

hi, so when I finish the use of kaptan (after erase disk installation) it just freeze an screen turns black
I need to restart manually in order to proceed
seen in former releases, but do not remeber since which
if this have already been reported feel free to close it

#### Package name & version you are having issues with or have a request for

> …2017-07

#### Used repositories

> …2017-07

#### Expected behaviour

> …proceed without a black screen beviours

#### Actual behaviour

> …freeze in a black screen, need to reboot, does not happen again

#### Steps to reproduce the problem

> …install, use kaptan, click finish, and it frezes

#### System info link created by Octopi > Tools > SysInfo
journalctl
> …https://gist.github.com/ki00/d5b7edd2c9af9ccde21a379e99389593

**Comment by demmm** [comment]
Kaptan has nothing to do with the installation process or "erase disk installation".

If you really have an issue with kaptan, then start kaptan from cli and post what settings you are adjusting, plus the cli output up clicking finish in kaptan.

So far this bug report is useless, since it does not look it has anything to do with Kaptan.

**Comment by ki00** [comment]
ah, ok, indeed every installation turns black, just after finish kaptan
I do not changed wallpaper, indeed

**Comment by ki00** [comment]
I changed window fusion , theme midna dark, left clic, links midna dark, icons midna dark, plasmoid activated

**Comment by demmm** [comment]
And cli output? log? 
Kaptan will turn black on clicking finish, since it restarts plasma.  Not clear from your report if it stays black.
Not clear either which version is used. thus again, not a useful bug report, but just making anyone who reads your reports guess what it is you have an issue with.  Please really **read** https://kaosx.us/docs

**Comment by ki00** [comment]
I post journalctl log, which log or command you need, sysinfo, what is cli output

**Comment by ki00** [comment]
is a screnshot before turning black? it turns black and continue black, I need to restart the computer

**Comment by demmm** [comment]
As in my first reply:
>If you really have an issue with kaptan, then start kaptan from cli and post what settings you are adjusting, plus the cli output up to clicking finish in kaptan.

**Comment by ki00** [comment]
the documentation of kaos is displayed in spanish here, so cli output do not know how to get
if you could write the command, I will do it
this are a screenshot before spectacle crashed /seems do not need to reinstall to run the error, just run kaptan again and it turns black the screen after final step, so that the windows are black, not the first run of kaptan

http://i67.tinypic.com/4tabue.png
http://i65.tinypic.com/14tjti.png

**Comment by ki00** [comment]
here is a sysinfo but is a different installation, however the same issue
https://gist.github.com/00590d9aaf87932321ed138dfe399e36

**Comment by demmm** [comment]
SysInfo is not what was asked (twice now), output of Kaptan is needed.

**Comment by ki00** [comment]
and which command is for it?

**Comment by demmm** [comment]
kaptan

**Comment by ki00** [comment]
i write the command and does not freeze when used kaptan
output:
https://pastebin.com/ZE0KYUL2

**Comment by demmm** [comment]
So now you can make all your adjustments in kaptan, then on finish all works correct?

**Comment by ki00** [comment]
at first think so, but later it freezes and need to restart manually

**Comment by demmm** [comment]
Please use kaptan one step at the time, see what change causes this, since I cannot reproduce.
For example, ONLY switch to a different wallpaper, if that is ok, restart and ONLY change widget style.

**Comment by ki00** [comment]
so I try one step at the time, and it works fine, then try combinations of two and same,
I try this three combination two times and it freezes (maybe there are more combinations):
Estilo de venta: Midna Dark
Esquema de color: Midna Dark
Tema de escritorio: Midna Dark

the log for the two times with the same combination (perhaps equal)
https://pastebin.com/iK9HiQRT
https://pastebin.com/08iF2SwP

hope this could be useful

**Comment by demmm** [comment]
Nope, still can't reproduce, changed all settings to midna dark on a fresh  install, no issues

**Comment by ki00** [comment]
I installed again kaos to solve another issue with tomoyo, but it continue in black (I can restart after pushing power button, but the changes are made), maybe is for this pc (intel)... I will continue testing regularly if something changes
Thanks

**Comment by demmm** [comment]
Please test one more thing, to see if this related to kaptan at all
Open system settings and make a bunch of changes, like different icon theme, plasma theme, color scheme.  Then close systemsettings, now run (in krunner Alt-F2):
```
kquitapp5 plasmashell && plasmashell
```
if plasma does not restart then, means it is not a kaptam issue.

**Comment by ki00** [comment]
seems that changes continue (before running the command on krunner), and wallpaper turns black but the lateral right panel continues (a quick hidden and appears again)

**Comment by demmm** [comment]
So it is not plasma that does not return, just a wallpaer path is not found.
Check by right clicking anywhere on the black screen, if `configure desktop` is an option, then this issue is not about plasma being stopped, but just a wallpaper not found.

**Comment by ki00** [comment]
hello today I tried again but before I load the wallpaper presentation from a folder, 
after I run the command in krunner it does not turn black, the presentation of pictures continues (do not know if this is the case of wallpaper missing)
and yes, the option "configurar escritorio" is an option after right click

**Comment by demmm** [comment]
Then I think this bug report can be closed, it is not an issue of plasma not restarting, but the use of a non-existing wallpaper (at least not in a usable path).
Re-open if you can set a way so it can be reproduced that plasma does not restart and a correct wallpaper path is used.
