### ISSUE TITLE
Segfault executing Godot 2.1.4

### ISSUE THREAD

**Issue by EQLucky** [KaOSx/apps#132]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> Godot - godot 2.1.4-1

#### Used repositories

> apps

#### Expected behaviour

> Launch the Godot Project Manager Window.

#### Actual behaviour

> Segfaulting as seen in the screenshot provided.
![screenshot_20170908_022107](https://user-images.githubusercontent.com/3908056/30190765-b4f052bc-943c-11e7-9199-3bf53dc8ebb6.png)
[EDIT] I've tried several parameters within the terminal, every single one provides the same info, except the --help one.

#### Steps to reproduce the problem

> Launch Godot via terminal. When launched from GUI, it closes immediately.

#### System info link created by Octopi > Tools > SysInfo

> https://gist.github.com/0797a06524e7ab3f779f153d82db7248

**Comment by demmm** [comment]
This looks to be a graphics issue, see line 24 of SysInfo:
https://gist.github.com/anonymous/0797a06524e7ab3f779f153d82db7248#file-qt_temp_189618174-L24

The journalctl errors point to even more, kwin failing to enable compositing.  

This probably is an installer issue since you seem to be having a hybrid system, but regular nvidia was installed.
To test this, please remove nvidia and re-install the free drivers:
```
sudo pacman -Rdd nvidia nvidia-utils
```
```
sudo pacman -Syu
```
```
sudo pacman -S xf86-video-nouveau libgl
```
and reboot
On reboot, check inxi -G to see if you now have opengl entries and to see if the intel or nvidia card is in use.

**Comment by EQLucky** [comment]
Thank you, Demm, you were completely right.
I re-installed my laptop recently, using the september iso with proprietary drivers. Until now, I wasn't using anything opengl demanding, until I launched Godot.

Using the free drivers solved the issue.

**Comment by demmm** [comment]
Please still show the output of `inxi -G` now.
Can you tell also how you did the install?  Selected non-free on start of live mode? 
This is a bug that should not have happened.

To use non-free again, you need to get the bumblebee packages:
https://kaosx.us/docs/hybrid_gfx/
https://kaosx.us/docs/hybrid_gfx/#bumblebee-for-nvidia-cards
PRIME might be the better option though......

**Comment by EQLucky** [comment]
`inxi -G` output: [https://pastebin.com/GLNzu5a5](url)

About the install, I just installed the system through the 2017.09 using the non-free drivers with no issues, having checked the checksum previously.

About the Nvidia issue, I stopped fighting against it in KaOS, even following the documentation and GoogleFu'ing it: it's impossible to make it work (use it flawlessly and without any serious incident) with proprietary drivers outside Fedora, Solus and/or Ubuntu. But that's another story.

**Comment by demmm** [comment]
Would you mind running a Live test for me?  Again boot in Live mode with non-free and there run `inxi -G`
and `pacman -Qs nvidia`.
On hybrid systems, it should not install the regular non-free.

For the non-free/bumblebee issue, please open a separate bug report:
https://github.com/KaOSx/main/issues
but it might be bumblebee just no longer works with latest kernels/mesa/xorg

**Comment by EQLucky** [comment]
Both outputs on this link: [https://pastebin.com/iZUwAieb](https://pastebin.com/iZUwAieb)

I will open a bug report regarding the nvidia issue soon with logs and info needed, thanks.

**Comment by demmm** [comment]
OK, this is a bug in the installer :(

I need to figure a way when the user selects non-free and has a hybrid system to not install nvidia, thanks for the reports, closing this issue now, since it has nothing to do with godot, but needs to be addressed in calamares.
