### ISSUE TITLE
google-chrome-62.0.3198 not load website mercadolibre 

### ISSUE THREAD

**Issue by tatizaffaroni** [KaOSx/apps#133]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> google-chrome-62.0.3198.0-1

#### Used repositories

> apps

#### Expected behaviour

> load the website normaly

#### Actual behaviour

> not load the website

#### Steps to reproduce the problem

> try  www.mercadolibre.com.ar

#### System info link created by Octopi > Tools > SysInfo

> …

**Comment by demmm** [comment]
That is not a KaOS issue, but how Chrome now handles ssl sites with wrong or dubious certificates.  Nothing that can be done here for that.
You can try to contact that site and let them know they need to update their https certificate.
