### ISSUE TITLE
Elisa music player doesn't show up

### ISSUE THREAD

**Issue by fjmorazan** [KaOSx/apps#134]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> elisa 0.0.6

#### Used repositories

> build repo

#### Expected behaviour

> The music player would appear after launch it from the menu

#### Actual behaviour

> Elisa player doesn't show its gui, only appears as a background process on ksysguard
#### Steps to reproduce the problem

> * Launch  the music player from the menu or the console
> * It will show a running process using a system monitor, but never the interface of the program

#### System info link created by Octopi > Tools > SysInfo

> https://gist.github.com/6c1e36afddb7320ae8297b9986e422d5

Error message when relaunching elisa with konsole after launch it from the menu
https://gist.github.com/6c1e36afddb7320ae8297b9986e422d5

**Comment by demmm** [comment]
Seems an upstream issue:
https://www.mail-archive.com/kde-devel@kde.org/msg09690.html

Will try a rebuild with the latest commits.  It can be an issue with Qt 5.9.2 and kirigami:
https://bugreports.qt.io/browse/QTBUG-64017

I'll also apply the mentioned patch to qt5-declarative.

**Comment by fjmorazan** [comment]
Now with the last update of those packages on [build], elisa works without issue :D

**Comment by demmm** [comment]
Not fixed, only works now because of using a commit from early September, any after fails to run.  Issue will stay open until upstream has a fix.

**Comment by demmm** [comment]
Issue fixed with latest Elisa builds.
