### ISSUE TITLE
Calendar related stuff on Akonadi doesn't work

### ISSUE THREAD

**Issue by fjmorazan** [KaOSx/apps#135]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> akonadi-calendar 17.08.2
> korganizer 17.08.2
#### Used repositories

> build repo
#### Expected behaviour

> Events from local and remote calendars should be displayed on _Digital clock_ plasmoid

#### Actual behaviour

> Korganizer and any other software that uses akonadi-calendar doesn't work properly

#### Steps to reproduce the problem

> Invoke Korganizer on konsole and it will show an [error](https://gist.github.com/fjmorazan/bcaffa7fd40c4d1eca3330a8bfaecafd) message
> Enable a Holiday on _Digital clock_ plasmoid, it won't show anything in the calendar panel

#### System info link created by Octopi > Tools > SysInfo

> https://gist.github.com/475c19c7da0dcded4805eef4e3d3b5bf

**Comment by demmm** [comment]
This is due to kcalcore being build on libical 3.0.0, the whole kmail stack needs to be build on that version, but fails to build so far.  It might be needed to revert the libical update.

**Comment by demmm** [comment]
Please update, libical was reverted to 2.0.0, now all builds for the kdepim/kmail stack.  Korganizer starts again here.  Don't close issue yet, KDE Apps won't move until frameworks 5.40.0 moves this Saturday.
