### ISSUE TITLE
Octpi doesn't start

### ISSUE THREAD

**Issue by zetomad** [KaOSx/apps#136]
#### Submission type

  - [x ] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for
Octopi
> …
after todya's upgrade
#### Used repositories
standard
> …

#### Expected behaviour

> …

#### Actual behaviour
doesn't start 
> …
octopi: /usr/lib/libQt5Core.so.5: version `Qt_5.10' not found (required by octopi)
#### Steps to reproduce the problem

> …

#### System info link created by Octopi > Tools > SysInfo

> …

**Comment by demmm** [comment]
Thanks for reporting, rebuild against Qt 5.9.3 will be up shortly.
