### ISSUE TITLE
Octopi Md5sum error after update notification

### ISSUE THREAD

**Issue by jigzila** [KaOSx/apps#138]
#### Submission

[x] Bug report

> Octopi

Checking core main apps... 

Mirror-check...

md5sum: /tmp/.1000mirrordb.tmp: No such file or directory
'core' is not synced.Do not update, wait for your mirror to sync. 
'main' is not synced. 
Do not update, wait for your mirror to sync.
'apps' is not synced.Do not update, wait for your mirror to sync. 

Command finished with errors!
 
&

Synchronizing databases...

error: failed retrieving file 'core.db' from mirror.math.princeton.edu : Connection timed out after 10000 milliseconds 
Syncing core 
error: failed retrieving file 'main.db' from mirror.math.princeton.edu : Connection timed out after 10001 milliseconds 
Syncing main 
error: failed retrieving file 'apps.db' from mirror.math.princeton.edu : Connection timed out after 10001 milliseconds 
Syncing apps 

Synchronizing databases... (pkgfile -u)

warning: download failed: https://mirror.math.princeton.edu/pub/kaoslinux/core/core.files: Failed to connect to mirror.math.princeton.edu port 443: Connection timed out 
warning: download failed: https://mirror.math.princeton.edu/pub/kaoslinux/main/main.files: Failed to connect to mirror.math.princeton.edu port 443: Connection timed out 
warning: download failed: https://mirror.math.princeton.edu/pub/kaoslinux/apps/apps.files: Failed to connect to mirror.math.princeton.edu port 443: Connection timed out 

Command finished OK!

**Comment by demmm** [comment]
This is not an Octopi issue, rather the used mirror, http://mirror.math.princeton.edu is down right this minute.  Edit your /etc/pacman.d/mirrorlist, and select a different mirror until princeton is back online.

**Comment by jigzila** [comment]
changed mirror > ctrl-D Sync Database > successfully upgrade system > reboot

I still get this error when launch octopi:

Checking core main apps... 

Mirror-check...

md5sum: /tmp/.1000mirrordb.tmp: No such file or directory
'core' is not synced. 
Do not update, wait for your mirror to sync.
'main' is not synced.Do not update, wait for your mirror to sync. 
'apps' is not synced.Do not update, wait for your mirror to sync. 

Command finished with errors!

**Comment by demmm** [comment]
Run `sudo pacman -Scc` to clear the faulty cache.

**Comment by jigzila** [comment]
Run the suggested command :

Cache directory: /var/cache/pacman/pkg/
:: Do you want to remove ALL files from cache? [y/N] y
removing all files from cache...

Database directory: /var/lib/pacman/
:: Do you want to remove unused repositories? [Y/n] y
removing unused sync repositories...

reboot

open octopi

Checking core main apps... 

Mirror-check...

md5sum: /tmp/.1000mirrordb.tmp: No such file or directory
'core' is not synced.Do not update, wait for your mirror to sync. 
'main' is not synced.Do not update, wait for your mirror to sync. 
'apps' is not synced.Do not update, wait for your mirror to sync. 

Command finished with errors!
