### ISSUE TITLE
mouse righ click after update not working

### ISSUE THREAD

**Issue by zetomad** [KaOSx/apps#139]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> KDE plasma Activities

#### Used repositories

> …

#### Expected behaviour

> middle & right click working

#### Actual behaviour

> only left click working

#### Steps to reproduce the problem

> just update the system 
#### System info link created by Octopi > Tools > SysInfo

> …

**Comment by demmm** [comment]
Make sure to add the asked for info, minimal needed is SysInfo, since this cannot be reproduced.

**Comment by demmm** [comment]
Make sure to update the system, and report if you still see this issue.

**Comment by demmm** [comment]
No further response from submitter.
