### ISSUE TITLE
kmymoney regression after last upgrade

### ISSUE THREAD

**Issue by zetomad** [KaOSx/apps#141]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> kmymoney 5.0.0-1

#### Used repositories

> core, main, apps

#### Expected behaviour

> online banking sync

#### Actual behaviour

> Accounts synchronization not workig at all

#### Steps to reproduce the problem

> start kmymoney, accounts sync stays grey

#### System info link created by Octopi > Tools > SysInfo

> https://gist.github.com/anonymous/bfd92fde4d1f1d1d03c33f3783edc0c1

**Comment by demmm** [comment]
To be sure of how this system is used, please post the output of:
```
pacman -Qi printer-driver-ptouch
```
and:
```
pacman -Qi kmymoney
```
Seems you were installing kmymoney versions not at all from KaOS (there is no pkgrel 3 for 5.0.0).

**Comment by zetomad** [comment]
here you go:
pacman -Qi kmymoney
Name                     : kmymoney
Version                  : 5.0.0-1
Beschreibung             : An finance manager for KDE with HBCI support
Architektur              : x86_64
URL                      : http://www.kmymoney.org/
Lizenzen                 : GPL
Gruppen                  : office
Stellt bereit            : Nichts
Hängt ab von             : karchive  kcoreaddons  kconfig  kconfigwidgets  ki18n  kcompletion  kcmutils  kitemmodels  kitemviews  kservice  kwallet
                           kiconthemes  kxmlgui  ktextwidgets  knotifications  kio  kholidays  gpgme  kcontacts  akonadi-contacts  akonadi
                           kidentitymanagement  kross  shared-mime-info  boost-libs  pulseaudio  libofx  libical  alkimia  kdiagram  kactivities  aqbanking
                           kdewebkit
Optionale Abhängigkeiten : Nichts
Benötigt von             : Nichts
Optional für             : Nichts
In Konflikt mit          : Nichts
Ersetzt                  : Nichts                                                                                                                              
Installationsgröße       : 38,01 MiB
Packer                   : Anke Boersma <demm@kaosx.us>
Erstellt am              : Mi 07 Feb 2018 12:05:12 CET
Installiert am           : Mo 19 Feb 2018 08:37:10 CET
Installationsgrund       : Ausdrücklich installiert
Installations-Skript     : Nein
Verifiziert durch        : SHA-256-Summe

pacman -Qi printer-driver-ptouch
Name                     : printer-driver-ptouch
Version                  : 1.4.2-3
Beschreibung             : printer driver Brother P-touch label printers
Architektur              : x86_64
URL                      : https://bitbucket.org/philpem/printer-driver-ptouch
Lizenzen                 : GPL
Gruppen                  : Nichts
Stellt bereit            : Nichts
Hängt ab von             : ghostscript  foomatic-db
Optionale Abhängigkeiten : Nichts
Benötigt von             : Nichts
Optional für             : Nichts
In Konflikt mit          : Nichts
Ersetzt                  : Nichts
Installationsgröße       : 226,00 KiB
Packer                   : Unknown Packager
Erstellt am              : Mo 19 Feb 2018 09:40:02 CET
Installiert am           : Mo 19 Feb 2018 09:42:46 CET
Installationsgrund       : Ausdrücklich installiert
Installations-Skript     : Nein
Verifiziert durch        : Nichts
althought I don't think that the printer-driver-ptouch is relevant here. And of course I did install the Kmymoney version from Kaos repositories (even reinstalled it yesterday!) It was working perfectly before upgrade!

**Comment by demmm** [comment]
Since your pacman -Qm shows quite a few packages not from the repo, and the version of kmymoney you initial reported as having issues is not from KaOS either:
```
[2018-02-19 08:28] [PACMAN] Running 'pacman -U <HOME_PATH>/Downloads/kmymoney-5.0.0-3-x86_64.pkg.tar.xz'
```
it is needed to know how you get these packages.  Using any from non KaOS repos, is known to break your install ans cannot be supported or debugged by KaOS.

**Comment by zetomad** [comment]
once again: the package is from Kaos, pls. look at:
Installationsgröße : 38,01 MiB
Packer : Anke Boersma demm@kaosx.us
Erstellt am : Mi 07 Feb 2018 12:05:12 CET
Installiert am : Mo 19 Feb 2018 08:37:10 CET

I do have another machine running Manjaro - there was no problem regarding this package! I think I'll give up on Kaos - this is the 3rd time that after upgrade sth is not working any more :(

**Comment by demmm** [comment]
As said, and still no reply, KaOS is not compatible with other repos.  You will always break your system if you do so otherwise.  Closing this now as invalid.

**Comment by demmm** [comment]
Though this bug report is not useful up til now, adding possible upstream link for possible resemblance:
https://bugs.kde.org/show_bug.cgi?id=390834
