### ISSUE TITLE
KCM_UFW cant add or remove rules

### ISSUE THREAD

**Issue by x11tete11x** [KaOSx/apps#15]
get an error when i try to add or remove a rule

http://i.imgur.com/622YSf4.png

other user can confirm: https://plus.google.com/101694767317281451820/posts/cyvZ1Zw6CWR

and Yoyo too

**Comment by demmm** [comment]
kcm-ufw is no longer available in the KaOS repos.
Please install ufw-frontends instead.
Closing this issue.
