### ISSUE TITLE
No network available at all, Glitch. 

### ISSUE THREAD

**Issue by ShalokShalom** [KaOSx/apps#160]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> … networkmanager 1.12.2

#### Used repositories

> … core, main, apps

#### Expected behaviour

> … Network is working

#### Actual behaviour

> … Neither WLAN nor ethernet is working. No connections are shown in the list. 

When connected via ethernet, the systray icon turns from orange into blue, as designated.
Reboots and `systemctl restart NetworkManager` do not solve the issue. 

The strange thing about this bug is that it initially appeared 2 months ago and disappeared from one day to the other. My network was not working for like 3 days and a lot of reboots and then working again magically. Then, it worked again without any change from my side. 

2 days ago, the bug reappeared and stayed until yesterday, again:
The bug disappears without any intervention from my side, I simply boot the device and it seems randomly working - or not. 

All this counts for all internet chips, so both in the device and also external (USB) dongles. 
It always effects all of them at the same time, when the bug happens. 

I can provide any additional logs which are helpful in this case. 

#### System info link created by Octopi > Tools > SysInfo

> … https://ptpb.pw/25QG

I do not expect this issue to be solved by KaOS, this bug report is mostly for the record.

**Comment by demmm** [comment]
Is this still an issue?

**Comment by ShalokShalom** [comment]
No, thanks.
