### ISSUE TITLE
installing QtCreator v4.7.1-1 creates duplicate desktop icons

### ISSUE THREAD

**Issue by bits4fun** [KaOSx/apps#166]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> qtcreator-4.7.1-1-x86_64.pkg.tar.xz

#### Used repositories

> Apps

#### Expected behaviour

> When installing latest QtCreator v4.7.1, it should generate a single entry in Development group

#### Actual behaviour

> Two entries are generated, with two different style icons.

#### Steps to reproduce the problem

> Just install from Octopi

#### screenshot
![double-qtcreator-icons](https://user-images.githubusercontent.com/2035390/46904374-6b6cf180-cee3-11e8-8c1c-4a42cac34827.png)

**Comment by bits4fun** [comment]
The package contents shows the two desktop icons. Probably Qt's own icon should be used:

![qtcreator-package-content](https://user-images.githubusercontent.com/2035390/46904610-47abaa80-cee7-11e8-98fe-bb4a622934e1.png)

**Comment by demmm** [comment]
Looks like qtcreator finally ships with a .desktop, I missed that.
This is no longer needed:
https://github.com/KaOSx/apps/blob/master/qtcreator/PKGBUILD#L47
You can check yourself too, remove the KaOS provided (now duplicate) .desktop:
```
sudo rm /usr/share/applications/qtcreator.desktop
```
Rebuild of qtcreator with this corrected will be up shortly.

**Comment by bits4fun** [comment]
Cool. Thanks... Enjoying the beauty of KaOS..
