### ISSUE TITLE
Fn key functionality to change graphic output scales too huge

### ISSUE THREAD

**Issue by ShalokShalom** [KaOSx/apps#168]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> … current updates on two different laptops 

#### Used repositories

> … core, main, apps

#### Expected behaviour

> … Switch output overlay scales well

#### Actual behaviour

> … 

![screenshot_20181103_142732](https://user-images.githubusercontent.com/6344099/47957147-2a7f6e80-dfb1-11e8-9347-87bbc9f51fad.png)

#### Steps to reproduce the problem

> … Press Fn + F4 on your notebook, respectively which combination will cause the pop-up.

**Comment by ShalokShalom** [comment]
This scales so huge just when I press the key combination. When I plug in another monitor or the beamer, the menu pops up regularly.

**Comment by demmm** [comment]
Very old, and not a KaOS/packaging issue. Closing. Please re-open if you can still replicate.
