### ISSUE TITLE
Every Rss plasmoids dont work

### ISSUE THREAD

**Issue by constantius24** [KaOSx/apps#171]
QML: file:///home/radek/.local/share/plasma/plasmoids/RSS_feeds/contents/ui/main.qml:9:34: Type FullRepresentation unavailable
file:///home/radek/.local/share/plasma/plasmoids/RSS_feeds/contents/ui/FullRepresentation.qml:2:1: module "QtQuick.XmlListModel" is not installed

**Comment by demmm** [comment]
And what app is this bug report about?

**Comment by constantius24** [comment]
qml-module-qtquick-xmllistmodel but in Kaos does not exist. Only RSS widgets dont work rest of widgets are working

**Comment by demmm** [comment]
This is a change in Qt 5.12, see https://forum.kaosx.us/d/2263-module-qtquick-xmllistmodel-is-not-installed/2 for a similar issue.  AFAIK, not a KaOS issue, but a change in Qt.

**Comment by constantius24** [comment]
https://ptpb.pw/CTQg

**Comment by demmm** [comment]
Found the commit that moved the needed files:
https://github.com/qt/qtxmlpatterns/commit/8c6e24329ecd65f364654b1ca2b6a273f0826a8b
Seems it is now part of xmlpatterns, IF it is build with qt5-declarative as new dependency.

**Comment by demmm** [comment]
Rebuild qt5-declarative & qt5-xmlpatterns is up.  Adding the declarative depend to xmlpatterns fixes the missing/moved xmlListModels.
You can try installing with:
```
sudo pacman -U http://kaosx.tk/repo/build/qt5-declarative-5.12.0-2-x86_64.pkg.tar.xz http://kaosx.tk/repo/build/qt5-xmlpatterns-5.12.0-2-x86_64.pkg.tar.xz
``` 
but make sure you have the 5.12.0-1 versions in your pacman cache, since I can't guarantee these new versions build on the huge openssl/perl update will work in the stable repos.  All plasmoids needing xmlListModels work here again.

**Comment by constantius24** [comment]
ok thanks a lot
i will try later

radek

śr., 12 gru 2018 o 11:54 demmm <notifications@github.com> napisał(a):

**Comment by constantius24** [comment]
installed - works

śr., 12 gru 2018 o 12:23 nn <domowy73@gmail.com> napisał(a):
