### ISSUE TITLE
subtitlecomposer requires recompilation

### ISSUE THREAD

**Issue by chelqo** [KaOSx/apps#172]
#### Submission type
  - [ X ] Bug report

#### Package name & version you are having issues with or have a request for
subtitlecomposer 0.6.6-2 

#### Used repositories
apps

#### Actual behaviour
ldd /usr/bin/subtitlecomposer | grep not
        libavcodec.so.57 => not found
        libavformat.so.57 => not found
        libavutil.so.55 => not found
        libswresample.so.2 => not found

**Comment by demmm** [comment]
Rebuild is up, will move soon to all users.  In the meantime, save to use with:
```
sudo pacman -U http://kaosx.tk/repo/build/subtitlecomposer-0.6.6-3-x86_64.pkg.tar.xz
```
Issue will be closed once it is in the [apps] repo.
