### ISSUE TITLE
Unable to use scons

### ISSUE THREAD

**Issue by fjmorazan** [KaOSx/apps#175]
#### Submission type

  - [X] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

>scons 3.0.4-2

#### Used repositories

>build repo

#### Expected behaviour
```
$ scons --version
SCons by Steven Knight et al.:
        script: v3.0.4.3a41ed6b288cee8d085373ad7fa02894e1903864, 2019-01-23 17:30:35, by bdeegan on kufra
        engine: v3.0.4.3a41ed6b288cee8d085373ad7fa02894e1903864, 2019-01-23 17:30:35, by bdeegan on kufra
        engine path: ['/usr/lib/python2.7/site-packages/SCons']
Copyright (c) 2001 - 2019 The SCons Foundation
```

#### Actual behaviour
```
$ scons --version
SCons import failed. Unable to find engine files in:
  /usr/lib/scons-3.0.4
  /usr/lib/scons-3.0.4
  /usr/local/lib/scons-3.0.4
  /usr/lib/python2.7/site-packages/scons-3.0.4
  /usr/lib/python2.7/site-packages/scons-3.0.4
  /usr/local/lib/python2.7/site-packages/scons-3.0.4
  /usr/lib/scons-3.0.4
  /usr/lib/scons
  /usr/lib/scons
  /usr/local/lib/scons
  /usr/lib/python2.7/site-packages/scons
  /usr/lib/python2.7/site-packages/scons
  /usr/local/lib/python2.7/site-packages/scons
  /usr/lib/scons
Traceback (most recent call last):
  File "/usr/bin/scons", line 195, in <module>
    import SCons.Script
ImportError: No module named SCons.Script
```

#### Steps to reproduce the problem
Running the build 3.0.4-2 of scons pkg and it will throw the previous error. Downgrading to scons-3.0.4-1 doesn't trigger the behaviour

#### System info link created by Octopi > Tools > SysInfo
https://gist.github.com/fjmorazan/d5dcca7c022e17497f9216d0f8314e06
> …

**Comment by demmm** [comment]
I have noticed this too yesterday (godot build failed on scons looking for python2), might be too early to move scons to python3.  Or it is time to make python3 the default.
Issue is that things look for /usr/bin/python, which still points to python2.
I'll revert the 3.0.4-2 python3 move for now, and won't redo until python3 is default.
