### ISSUE TITLE
Firefox 66 unable to open any webpage

### ISSUE THREAD

**Issue by ShalokShalom** [KaOSx/apps#176]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> … Firefox 66

#### Used repositories

> … core, main, apps

#### Expected behaviour

> … Open webpage

#### Actual behaviour

> … Every single webpage unable to open due to security error:

![Screenshot_20190323_093540](https://user-images.githubusercontent.com/6344099/54863920-10231300-4d4f-11e9-929c-f7264003be12.png)

#### Steps to reproduce the problem

> … Open any webpage

#### System info link created by Octopi > Tools > SysInfo

> … https://github.com/KaOSx/apps/issues/177

**Comment by demmm** [comment]
Update the system and re-open if you issue is still present.
See:
https://forum.kaosx.us/d/2329-firefox-problem-your-connection-is-not-secure
