### ISSUE TITLE
Octopi: SysInfo broken

### ISSUE THREAD

**Issue by ShalokShalom** [KaOSx/apps#177]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> … Octopi 0.9.0.81

#### Used repositories

> … core, main, apps

#### Expected behaviour

> … SysInfo Link posted

#### Actual behaviour

> … SysInfo Link does not appear

#### Steps to reproduce the problem

> … Create a SysInfo via Octopi

See: http://sendvid.com/mrhh0ktg

**Comment by demmm** [comment]
https://github.com/ptpb/pb/issues/246
I will leave the issue open here, but this needs to be changed in Octopi itself.  I'll open a bug report in Octopi and see how we can implement SysInfo again.

**Comment by ShalokShalom** [comment]
Just change the provider?

**Comment by demmm** [comment]
Unfortunately, not that simple.
To follow see:
https://github.com/aarnt/octopi/issues/370
None of the paste services tried so far work with c++ code, it probably will be e rewrite and abandon the use of any pastebin, but create a log file locally instead.

**Comment by ShalokShalom** [comment]
You could post this logfile automatically to some other pastebin service then with inotify.

So simply watch the dir where you save the log files you mentioned and upload when a new file appears.

Sounds simple :)
