### ISSUE TITLE
Libreoffice: Image import fails in Writer

### ISSUE THREAD

**Issue by ShalokShalom** [KaOSx/apps#178]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> …Libreoffice 6.2.2.2

#### Used repositories

> … core; main; apps

#### Expected behaviour

> … Picture loads in Writer

#### Actual behaviour

> … Picture loads in Impress, while not in Writer

#### Steps to reproduce the problem

> … Load Writer, insert picture

#### System info link created by Octopi > Tools > SysInfo

> … no SysInfo currently

See the video: 
http://sendvid.com/i7fkuxhj

**Comment by demmm** [comment]
Can't reproduce.  Make sure this is not an issue with your user.

**Comment by ShalokShalom** [comment]
Thanks dear. I deleted the libreoffice folder in .config
Now it works :)
