### ISSUE TITLE
TLP depends on tp_smapi and acpi_call

### ISSUE THREAD

**Issue by bvbfan** [KaOSx/apps#18]
[toni@toni-sony ~]$ sudo pacman -Qi tlp
Name           : tlp
Version        : 0.7-1
Description    : Linux Advanced Power Management
Architecture   : x86_64
URL            : http://linrunner.de/en/tlp/docs/tlp-linux-advanced-power-management.html
Licenses       : GPL2  GPL3
Groups         : None
Provides       : None
Depends On     : bash  hdparm  perl  rfkill  wireless_tools  networkmanager
                 smartmontools  iw  tp_smapi  acpi_call
Optional Deps  : None
Required By    : None
Optional For   : None
Conflicts With : pm-utils
Replaces       : None
Installed Size : 259,00 KiB
Packager       : Anke Boersma <demm@kaosx.us>
Build Date     :  1.02.2015 (нд) 17,47,15 EET
Install Date   :  7.02.2015 (сб) 12,49,23 EET
Install Reason : Explicitly installed
Install Script : No
Validated By   : SHA256 Sum

According to http://linrunner.de/en/tlp/docs/tlp-linux-advanced-power-management.html
tp-smapi - optional ThinkPad only, tp-smapi is needed for battery charge thresholds and ThinkPad specific status output of tlp-stat
acpi-call - optional ThinkPad only, acpi-call is needed for battery charge thresholds on Sandy Bridge and newer models

**Comment by demmm** [comment]
Not clear what the the issue is.  You want KaOS to ship a cripled package, by removing functions that users need to guess they could be included?

**Comment by bvbfan** [comment]
Issues:
1. Kernel_load_modules.service fails due to tp-smapi can't be applied, missing thinkpad hardware
2. Acpi tries to be applied systemd tells
acpi_call: cannot get handle: Error: AE_NOT_FOUND
on boot time

**Comment by demmm** [comment]
Thanks for explaining, rebuild will be up asap.

**Comment by bvbfan** [comment]
Issues are fixed. All works as expected.

**Comment by demmm** [comment]
Issue will be closed once tlp moves to [main]
