### ISSUE TITLE
Falkon failed open dozen URLs from command line with one command.

### ISSUE THREAD

**Issue by SzykCech4** [KaOSx/apps#187]
#### Submission type

  - [ ] Bug report

#### Package name & version you are having issues with or have a request for
> 3.1.0

#### Used repositories

> ?

#### Expected behaviour

> It should open all pages in tabs. This is use full for me to have file with all news URLs and load it form script.

#### Actual behaviour

> Falkon failed open dozen URLs from command line with one command. But this should be handled according to failkon -h result.

#### Steps to reproduce the problem

> Just try command: 
falkon https://kresy.pl/ https://kopalniawiedzy.pl/wiadomosci https://www.youtube.com/user/OpcjaSpoleczna/videos https://defence24.pl/ https://www.altair.com.pl/ https://kaosx.us/news https://pointieststick.com/2019/10/13/this-week-in-kde-plasma-5-17-approaches/ https://www.qt.io/blog  http://www.benchmark.pl/kategoria/systemy-operacyjne-pc.html https://www.linuxinsider.com/perl/section/linux-developer/ https://www.linuxtoday.com/ http://apollo-core.com/knowledge.php https://exec.pl/ https://www.ppa.pl/ https://www.youtube.com/channel/UCe5Dq2HfS7IbF67qPnAuA5w/videos https://www.youtube.com/user/SPInkafilmstudio/videos

#### System info link created by Octopi > Tools > SysInfo

> [octopi-sysinfo-2052296094.log](https://github.com/KaOSx/apps/files/3763713/octopi-sysinfo-2052296094.log)

This report is copy bug reported: https://bugs.kde.org/show_bug.cgi?id=413195

**Comment by demmm** [comment]
So this is a packaging bug?  Or have you checked upstream whether Falkon can actually handle this?

**Comment by SzykCech4** [comment]
What do you mean by "packaging bug"?
I don't "checked upstream" just have use it for a week since I installed KaOS. I wrote just what I encounter when I customize options to my needs and preferences.

**Comment by SzykCech4** [comment]
I report this bug here because I found this site and notice that no body from KDE answer since few days.

**Comment by demmm** [comment]
Falkon is not developed by KaOS, KaOS only packages what upstream (Falkon developers) releases.  If this is not reported anywhere upstream or other distros, then it must be a packaging issue (how KaOS builds/handles the dependencies).

**Comment by demmm** [comment]
So far can't find if this is supported in Falkon/QtWebEngine.  Even for Chrome it is not an option, unless you install some extension, so I really doubt this is supported, looks like the -h output just refers to the fact, that you choose urls.
Will mark as upstream, unless the KDE (upstream) bug report indicates otherwise.

**Comment by SzykCech4** [comment]
Did you see this:
```
Sposób użycia: falkon [opcje] [URL...]
QtWebEngine based browser

Opcje:
  -h, --help                   Wyświetla tę pomoc.
  -v, --version                Wyświetla numer wersji.
  -a, --authors                Displays author information.
  -p, --profile <profileName>  Starts with specified profile.
  -e, --no-extensions          Starts without extensions.
  -i, --private-browsing       Starts private browsing.
  -o, --portable               Starts in portable mode.
  -r, --no-remote              Starts new browser instance.
  -t, --new-tab                Opens new tab.
  -w, --new-window             Opens new window.
  -d, --download-manager       Opens download manager.
  -c, --current-tab <URL>      Opens URL in current tab.
  -u, --open-window <URL>      Opens URL in new window.
  -f, --fullscreen             Toggles fullscreen.
  --wmclass <WM_CLASS>         Application class (X11 only).

Argumenty:
  URL                          URLs to open

```
Consider last line: `URLs to open` - this is exactly what I want to do. I want open all my pages (URLs) stored in text file by external script. But now it opens all of them in the same tab (so only last of them is fully loaded and finaly visible). This is feature bug. It should open all pages (URLs) in separate tabs.

This is especially important from user point of view because he/she can's open all pages from right click menu on the bookmark group node. I prefer open all my pages from the separate script because this way:
+ I open them faster.
+ I can gain control over my URLs (I can backup them with rest of my files) - this is real problem - lost bookmarks with instal/reinstal systems.
+ I can use power of my mind.
+ I can use Linux power.

Of course open all URLs by right click on the bookmark grouping node is standard browser feature since years, and it is pity that Falcon can't do it. Other pity is that it does not allow to create custom bookmark groups (but as I wrote: I prefer scripts over clicking).
Any way I like Falcon and use it daily.

**Comment by demmm** [comment]
Yes, I know the Falkon help file, again, can't find any ref to this being possible, so only option now is to wait for an answer from the Falkon developers.

**Comment by demmm** [comment]
Closing as won't fix, Falkon no longer has a maintainer. Not a KaOS bug.
