### ISSUE TITLE
Krusader: unable to make shortcut with the meta key in visual shortcut editor.

### ISSUE THREAD

**Issue by SzykCech4** [KaOSx/apps#188]
#### Submission type

  - [ ] Bug report

#### Package name & version you are having issues with or have a request for

> Krusader v2.7.2

#### Used repositories

> ?

#### Expected behaviour

> Shortcut editor should properly handle meta key combination.

#### Actual behaviour

> I am unable to make shortcut with the meta key in visual shortcut editor. The only option (workaround) is edit config file in text editor.

#### Steps to reproduce the problem

> 1. Run Krusader.
2. Open from menu: Settings->Shortcut editor.
3. Try set some shortcut with the meta key (checked for meta+` combination).

#### System info link created by Octopi > Tools > SysInfo

> …
[octopi-sysinfo-2052296094.log](https://github.com/KaOSx/apps/files/3763773/octopi-sysinfo-2052296094.log)

This report is copy of bug report: https://bugs.kde.org/show_bug.cgi?id=413175

**Comment by demmm** [comment]
OK, please close the bug report in KDE, since this is clearly in KaOS only, thus a packaging bug, will investigate why this occurs.

**Comment by SzykCech4** [comment]
Done.

**Comment by demmm** [comment]
Since KaOS is using far newer versions then Debian, Kubuntu and Neon (latter only use up to date KDE, not latest toolchain or Qt), what versions of Qt did you have when you did not see this behavior?

**Comment by demmm** [comment]
Seems only an issue with the Meta key, can you reproduce when using something like Ctrl - A as assigned shortcut?

**Comment by demmm** [comment]
This is not a Krusader issue, you can reproduce in any KDE app, try for example in Kate, Meta key is not registered.  This looks like an upstream bug after all, did you try in Debian, Kubuntu, Neon with Plasma 5.17, Frameworks 5.63.0?  Or where they using older versions?

**Comment by SzykCech4** [comment]
They were some older versions. Newest version was KDE 5.16.5 in KDE NEON but I have WinDos 10 and KaOS only now. In KDE 5.16.5 i don't have such problems.

**Comment by demmm** [comment]
I'll check the Plasma bug reports, this is probably a Plasma 5.17 introduced bug (I think I saw some met keys issues mentioned in IRC in the plasma channel).

**Comment by demmm** [comment]
There is a bug report for this on Wayland sessions:
https://bugs.kde.org/show_bug.cgi?id=403509
So, looks like this bug now also effects X.
