### ISSUE TITLE
Midnight Commander (mc) is not usable at all!!!

### ISSUE THREAD

**Issue by SzykCech4** [KaOSx/apps#190]
#### Submission type

  - [ ] Bug report

#### Package name & version you are having issues with or have a request for

> mc --version
GNU Midnight Commander 4.8.23
Zbudowano za pomocą biblioteki GLib 2.60.4
Używanie biblioteki S-Lang z bazą danych terminfo
Z wbudowanym edytorem
Z domyślną obsługą podpowłoki
Z obsługą wykonywania działań w tle
Z obsługą myszy w xterm i konsoli Linux
Z obsługą zdarzeń X11
Z obsługą wielu języków
Z obsługą wielu stron kodowych
Wirtualne systemy plików: cpiofs, tarfs, sfs, extfs, ftpfs, sftpfs, fish, smbfs
Typy danych: char: 8; int: 32; long: 64; void *: 64; size_t: 64; off_t: 64;

#### Used repositories

> ?

#### Expected behaviour

> Esential feature of mc is ability to navigate in directory content with arrow keys.

#### Actual behaviour

> Arrow key navigation not works at all!

#### Steps to reproduce the problem

> 1. $ pacman -S mc
2. $ mc
3. Try use arrow keys to navigate in directory.

#### System info link created by Octopi > Tools > SysInfo

> [octopi-sysinfo-967650891.log](https://github.com/KaOSx/apps/files/3801650/octopi-sysinfo-967650891.log)

**Comment by demmm** [comment]
Does it help when you set `TERM=xterm`?

**Comment by SzykCech4** [comment]
I am not sure what you mean in the sense where I am supose to write this. Anyway I would avoid this.

**Comment by demmm** [comment]
Please test with new/rebuild versions:
```
sudo pacman -U http://kaosx.tk/repo/build/slang-2.3.2-1-x86_64.pkg.tar.xz http://kaosx.tk/repo/build/mc-4.8.23-2-x86_64.pkg.tar.xz
```

**Comment by SzykCech4** [comment]
Now it works! Thank you!

**Comment by demmm** [comment]
Thanks for reporting.....this must have been broken a while.

**Comment by demmm** [comment]
Will close the issue once both packages have moved to the stable repos.
