### ISSUE TITLE
Account wich connection problem in system prefferents

### ISSUE THREAD

**Issue by LinuxCuba** [KaOSx/apps#194]
#### Submission type

  - [x ] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> kaccount-integrations

#### Used repositories

> official

#### Expected behaviour

> Show config prefferents the accounts. 

#### Actual behaviour

>  In system prefferents, Account wich online, show this error, 
An error occurred loading the QML file.
file:///usr/share/kpackage/kcms/kcm_kaccounts/contents/ui/Account.qml:31 module "Ubuntu.OnlineAccounts" is not installed

#### Steps to reproduce the problem

> Go to system prefferents, Connection Accounts.

#### System info link created by Octopi > Tools > SysInfo

> 
----------------------------------------------------------------------------------------------------------
cat /etc/KaOS-release
----------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------
inxi -Fxz
----------------------------------------------------------------------------------------------------------

System:    Host: <HOSTNAME> Kernel: 5.4.7-1 x86_64 bits: 64 compiler: gcc v: 9.2.0 
           Desktop: KDE Plasma 5.17.4 Distro: KaOS 2020 
Machine:   Type: Desktop System: Gigabyte product: Z370 HD3 v: N/A serial: <filter> 
           Mobo: Gigabyte model: Z370 HD3-CF v: x.x serial: <filter> 
           UEFI [Legacy]: American Megatrends v: F13 date: 08/13/2019 
Battery:   Device-1: hidpp_battery_0 model: Logitech Wireless Keyboard 
           charge: 55% (should be ignored) status: Discharging 
CPU:       Topology: 6-Core model: Intel Core i7-8700 bits: 64 type: MT MCP arch: Kaby Lake rev: A 
           L2 cache: 12.0 MiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 76799 
           Speed: 800 MHz min/max: 800/4600 MHz Core speeds (MHz): 1: 800 2: 800 3: 800 4: 801 
           5: 800 6: 800 7: 800 8: 800 9: 800 10: 800 11: 800 12: 800 
Graphics:  Device-1: Intel UHD Graphics 630 vendor: Gigabyte driver: i915 v: kernel 
           bus ID: 00:02.0 
           Display: x11 server: X.Org 1.20.6 driver: intel unloaded: modesetting,vesa 
           resolution: 1920x1080~60Hz, 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel UHD Graphics 630 (Coffeelake 3x8 GT2) 
           v: 4.5 Mesa 19.2.8 direct render: Yes 
Audio:     Device-1: Intel 200 Series PCH HD Audio vendor: Gigabyte driver: snd_hda_intel 
           v: kernel bus ID: 00:1f.3 
           Device-2: Logitech Notebook Deluxe type: USB driver: gspca_zc3xx,snd-usb-audio 
           bus ID: 1-9:5 
           Device-3: DisplayLink type: USB driver: cdc_ncm,snd-usb-audio bus ID: 2-8.2:3 
           Sound Server: ALSA v: k5.4.7-1 
Network:   Device-1: Intel Ethernet I219-V vendor: Gigabyte driver: e1000e v: 3.6.0-NAPI 
           port: f040 bus ID: 00:1f.6 
           IF: eno1 state: up speed: 1000 Mbps duplex: full mac: <filter> 
           IF-ID-1: enp0s20f0u8u2i5 state: down mac: <filter> 
Drives:    Local Storage: total: 1.13 TiB used: 957.35 GiB (82.9%) 
           ID-1: /dev/sda vendor: Seagate model: ST1000DM003-1ER162 size: 931.51 GiB 
           ID-2: /dev/sdb vendor: Kingston model: SHPM2280P2H 240G size: 223.57 GiB 
Partition: ID-1: / size: 40.70 GiB used: 17.79 GiB (43.7%) fs: xfs dev: /dev/sdb2 
           ID-2: /home size: 175.79 GiB used: 159.92 GiB (91.0%) fs: ext4 dev: /dev/sdb3 
           ID-3: swap-1 size: 4.03 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/sdb4 
Sensors:   System Temperatures: cpu: 27.8 C mobo: 16.8 C 
           Fan Speeds (RPM): N/A 
Info:      Processes: 258 Uptime: 44m Memory: 15.51 GiB used: 3.20 GiB (20.6%) Init: systemd 
           runlevel: 5 Compilers: gcc: 9.2.0 clang: 9.0.1 Client: Unknown Client: octopi 
           inxi: 3.0.37 

----------------------------------------------------------------------------------------------------------
journalctl -b -p err
----------------------------------------------------------------------------------------------------------

-- Logs begin at Wed 2020-01-08 14:52:09 CST, end at Wed 2020-01-08 15:36:01 CST. --
ene 08 14:52:34 <HOSTNAME> pulseaudio[1055]: [pulseaudio] bluez5-util.c: GetManagedObjects() failed: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
ene 08 14:53:41 <HOSTNAME> plasmashell[993]: Don't know how to handle layout QVBoxLayout(0xb2e7970, name = "verticalLayout_4")
ene 08 14:56:00 <HOSTNAME> plasmashell[993]: Don't know how to handle layout QVBoxLayout(0xb425660, name = "verticalLayout_4")
ene 08 14:56:05 <HOSTNAME> plasmashell[993]: Don't know how to handle layout QVBoxLayout(0xf8e22c0, name = "verticalLayout_4")

**Comment by demmm** [comment]
Test if accounts-qml-module is now a required depend for kaccounts-integrations:
```
sudo pacman -S accounts-qml-module
```
Does that fix the issue?

**Comment by demmm** [comment]
New Purpose will move to all users once Frameworks 5.66 is released coming Saturday.

**Comment by demmm** [comment]
This is a new way for kaccounts-integration 19.12, and one which upstream did not do properly:
https://github.com/KDE/kaccounts-integration/commit/feb0b036da1ca5a90309f20caa8ee3329da921ed#diff-87570dfdde40304d3e775f1f5a645e0e
They added the need for ubuntu accounts in the qml file, but did not add a new need in the cmake file, so really this is an upstream issue......

**Comment by LinuxCuba** [comment]
> Test if accounts-qml-module is now a required depend for kaccounts-integrations:
> 
> ```
> sudo pacman -S accounts-qml-module
> ```
> 
> Does that fix the issue?

Thanks Demmm, it was solved in part, only googles accounts are shown, I have other xmpp accounts previously that are not shown.
