### ISSUE TITLE
Media Player Widget without icon in system tray

### ISSUE THREAD

**Issue by ErSoul** [KaOSx/apps#196]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> …

#### Used repositories

Server = https://mirror.math.princeton.edu/pub/kaoslinux/$repo
Server = http://mirrors.redcorelinux.org/kaosx/$repo
Server = http://mirror6.layerjet.com/kaos/$repo
Server = https://mirror.alpix.eu/kaos/$repo
Server = https://kaos-frankfurt.tk/repo/$repo
Server = http://193.86.184.157/kaos/$repo
Server = http://kaos.youm.org/$repo
#Server = http://ftp.wa.co.za/pub/kaos/$repo
Server = http://mirror.dacentec.com/kaosx/$repo
Server = http://kaosx.tk/repo/$repo
Server = https://repo.kaosx.us/$repo
Server = https://mirror.freedif.org/KaOS/$repo

#### Expected behaviour

There should be at least an icon indicating that there's some media playing in the system tray.

#### Actual behaviour

Actually it shows nothing and didn't know it existed until noted an empty space in my tray icon.

#### Steps to reproduce the problem

Not sure... this came with the last installation image published in the web page. Though is my first time that I install this distro.

#### System info link created by Octopi > Tools > SysInfo

[octopi-sysinfo-460300162.log](https://github.com/KaOSx/apps/files/4196109/octopi-sysinfo-460300162.log)

**Comment by demmm** [comment]
What desktop theme in use?  Tried with a different them? Playing media through which app shows this (so far I have only noticed with chrome)?

**Comment by demmm** [comment]
Never mind, found the issue in the Midna icon theme, there actually are icons showing, but they are white on light gray, so invisible unless you hover over them (even then barely visible).  New icons will be added.
