### ISSUE TITLE
upstreaming things

### ISSUE THREAD

**Issue by flying-sheep** [KaOSx/apps#20]
hi, i’d like to see the PKGBUILDs in the AUR that aren’t there yet

is this possible?

**Comment by demmm** [comment]
No idea what you are asking....
If you want to add PKGBUILDs from KaOS to AUR, you are free to do so of course.
KaOS itself has nothing to do with Arch though, only uses their package manager.

**Comment by flying-sheep** [comment]
ah ok, i thought it would use arch packages, sorry.

and thanks for allowing me to put the PKGBUILDs on the AUR.

KaOS looks awesome i might switch for new PCs :)

**Comment by demmm** [comment]
Closing this issue now, leaving some links for reference should you be interested in what KaOS really is:
http://kaosx.us/faq/#Isn8217t_KaOS_just_another_Arch_based_distributionWhat_is_different_with_Chakra
http://kaosx.us/faq/#What_is_the_target_user

And from the Home page:
```
The idea behind KaOS is to create a tightly integrated rolling and transparent distribution for the modern desktop, **build from scratch** with a very specific focus.
```
