### ISSUE TITLE
Unable to add SMB folder in Dolphin

### ISSUE THREAD

**Issue by drijen** [KaOSx/apps#200]
#### Submission type

  - [ X] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> Dolphin 20.04.03

#### Used repositories

> Main, Fresh Install

#### Expected behaviour

> Adding a network smb share dialog should prompt for a user/password

#### Actual behaviour

> Dialog reports unable to connect to server

#### Steps to reproduce the problem

> Dolphin -> Network -> Add Network Folder 
                                           -> Select Microsoft Windows Network Drive -> Next -> <information> -> Connect

Suspect issue KDE  Net Attach related, smbclient will list shares as expected:

 drijen  ~  smbclient -L 192.168.0.199 -U <username_redacted>
smbclient: Can't load /etc/samba/smb.conf - run testparm to debug it
Enter WORKGROUP\<redacted>'s password: 

        Sharename       Type      Comment
        ---------       ----      -------
        Media           Disk      Plex Libraries
        Null            Disk      Primary Bitbucket
        IPC$            IPC       IPC Service ()
        Plex            Disk      Plex metadata storage
        usbshare1       Disk      Western Digital Technologies, Inc.

SMB1 disabled -- no workgroup available

#### System info link created by Octopi > Tools > SysInfo

>[octopi-sysinfo-203510847.log](https://github.com/KaOSx/apps/files/4978656/octopi-sysinfo-203510847.log)

**Comment by demmm** [comment]
Did you follow https://kaosx.us/docs/samba/ to enable smb properly?

**Comment by demmm** [comment]
No further response from submitter, closing.
