### ISSUE TITLE
Flatpak apps have issues in OpenFile function

### ISSUE THREAD

**Issue by la-manti** [KaOSx/apps#201]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

_Note: This is not a issue in other distros as far as I tested._

#### Package name & version you are having issues with or have a request for

> Flatpak 1.8.2 and some of its apps

#### Used repositories

> Standard KaOS repo/flathub

#### Expected behaviour

> Inside an app, when you click "Open File" or use shortcuts to do it, a window associated to a File Manager would open so you select a file to open.

#### Actual behaviour

> Some Flatpak apps doesn't open this window. (It doesn't affect packaged apps in KaOS repositories)

**Affected apps**
Firefox (all functions of opening a directory)
Avidemux
Kdenlive
Notepadqq
qBitTorrent
Kate
MKVToolNix (Add files)
VLC Media Player

**Non-affected apps**
LibreOffice
FreeFileSync
fre:ac
GIMP
Audacity
Discord

(this is the list of apps I use, I don't know about other apps in Flathub repo)

#### Steps to reproduce the problem

> Open one of the affected apps and try to open a file or redirect to File Manager.

#### System info link created by Octopi > Tools > SysInfo

> [octopi-sysinfo-3293304474.log](https://github.com/KaOSx/apps/files/5169046/octopi-sysinfo-3293304474.log)

#### Extra information
I run Avidemux, Kdenlive and qbittorrent in terminal. The output when you try to use the function is:

**Avidemux**
```
 [HandleAction] 14:09:40-218  ************ OPEN_VIDEO **************
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
```

**Kdenlive** and **qbittorrent** 
```
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
```

**Comment by demmm** [comment]
Not clear if you are reporting about flatpak apps only, since most apps you list are in the KaOS repo.  You have an issue with Firefox or Libreoffice from repo (as examples)?  And if not from repo, why use flatpaks instead of native?

**Comment by la-manti** [comment]
> Not clear if you are reporting about flatpak apps only, since most apps you list are in the KaOS repo. You have an issue with Firefox or Libreoffice from repo (as examples)? And if not from repo, why use flatpaks instead of native?

**Comment by demmm** [comment]
Why close instead of answering?

**Comment by la-manti** [comment]
> Why close instead of answering?

Sorry, I clicked wrongly XD

**Comment by demmm** [comment]
Please try installing xdg-desktop-portals, this might be a missing depend for flatpak.

**Comment by la-manti** [comment]
> Not clear if you are reporting about flatpak apps only, since most apps you list are in the KaOS repo. You have an issue with Firefox or Libreoffice from repo (as examples)? And if not from repo, why use flatpaks instead of native?

Well, I'm testing a way to backup my apps through distros without the needing of reinstall all the time. And the flatpak apps are faster updated than the official repos from distros.

**Comment by la-manti** [comment]
> Please try installing xdg-desktop-portals, this might be a missing depend for flatpak.

Oh, let's try it.

**Comment by demmm** [comment]
>And the flatpak apps are faster updated than the official repos 
I doubt you will see that in KaOS, apps are updated as they are released (libreoffice for example is already at 7.0.1.2 in the build repo, waiting for upstream to officially release before moving to all users), but your choice of course.
So I take you have an issue with flatpak Friefox?

**Comment by la-manti** [comment]
> > Please try installing xdg-desktop-portals, this might be a missing depend for flatpak.
> 
> Oh, let's try it.

Didn't work

**Comment by la-manti** [comment]
> So I take you have an issue with flatpak Firefox?

Yes.

**Comment by la-manti** [comment]
Do you use some flatpak listed?

**Comment by demmm** [comment]
Not using any (against them really, repeatedly adding unknown version of already installed system libraries make no sense imo).
Depending on bug reports for issues.

**Comment by demmm** [comment]
The xdg-desktop-portal service started? Or did not check?

**Comment by la-manti** [comment]
> The xdg-desktop-portal service started? Or did not check?

I installed, rebooted the computer, but it didn't work. I don't know if it started though. Is it a service?

**Comment by la-manti** [comment]
> Not using any (against them really, repeatedly adding unknown version of already installed system libraries make no sense imo).

It's the way they work, on sandboxes. They don't use libraries and runtimes from the system.

**Comment by demmm** [comment]
>It's the way they work, on sandboxes. They don't use libraries and runtimes from the system.

Exactly, so that means you have multiple versions of many libraries installed, instead of using an app build on system libraries, (and don't start with the system integration....)

**Comment by la-manti** [comment]
> Issue found, xdg-desktop-portal needed a newer version to work with current pipewire (and is needed to have flatpak work with file dialogs).
> New xdg-desktop-portal is up in the build repo, rebuild flatpak will follow shortly.

Are you saying the package of flatpak was updated in the repositories, but the package of xdg-desktop-portal was outdated?

**Comment by demmm** [comment]
>xdg-desktop-portal was outdated?
No, not outdated, had to use a pre-release to make it work with current pipewire, upstream is not syncing what they release......

**Comment by la-manti** [comment]
> > It's the way they work, on sandboxes. They don't use libraries and runtimes from the system.
> 
> Exactly, so that means you have multiple versions of many libraries installed, instead of using an app build on system libraries, (and don't start with the system integration....)

It's the proposal of Flatpak project. It works on system you have just flatpak option to run an application. Compiling is a hard work. XD

But I confess I like flatpak even if it's not the best option in the current system, like KaOS, where you can find some apps available.

**Comment by demmm** [comment]
They probably use a different way to access portals.

**Comment by demmm** [comment]
Needed packages just moved to the [apps] repo, once your mirror is synced, update.

**Comment by la-manti** [comment]
Alright.
