### ISSUE TITLE
opt in PATH

### ISSUE THREAD

**Issue by ShalokShalom** [KaOSx/apps#202]
I have no idea, why VSCodium has its own opt directory, while I suggest including it in the PATH, so I can start it from the command line. 

I do this now for myself, while I recommend this for all users. 

Just tried all possible binary names, till I discovered its actually not in usr/bin

**Comment by demmm** [comment]
Any application that ships with it's own libraries (not compiled) always installs in opt, examples blender, opera, chrome.

**Comment by ShalokShalom** [comment]
Well, that is fine. Can we put it in PATH?

I also discovered that many extensions don't work for VSCodium, offtopic: https://github.com/VSCodium/vscodium/issues/713
I would rather prefer VScode, while I guess this decision has been decided.
