### ISSUE TITLE
AVIF support in kimageformats

### ISSUE THREAD

**Issue by novomesk** [KaOSx/apps#203]
Hello,
I would suggest to build kimageformats with AVIF formats support.

It would be necessary to add libavif as dependency
and the libavif must be build with av1 encoders/decoders (libaom and dav1d).

**Comment by demmm** [comment]
So far no-one in KaOS has mentioned a need for AVIF formats. Care to elaborate what the benefits are?  Since KaOS has limited repos (https://kaosx.us/#goals), thus adding 3-4 extra packages for one option needs to benefit more then one user.  Adding new also means removing others, repos won't just expand.

**Comment by novomesk** [comment]
AVIF is modern image format which is excellent in preserving acceptable image quality when file size is very small.

AVIF can be used by websites, browsers have partial support already:

https://caniuse.com/avif

https://jakearchibald.com/2020/avif-has-landed/

https://medium.com/vimeo-engineering-blog/upgrading-images-on-vimeo-620f79da8605

https://netflixtechblog.com/avif-for-next-generation-image-coding-b1d75675fe4

GIMP supports AVIF, Krita 5 will support it too.

KaOS supports another new image format JXL (via jpeg-xl and my qt-jpegxl-image-plugin) while other distros support AVIF and haven't added Jpeg XL yet.

I think it will be good to support both AVIF and JXL, to make these new formats successful.

libavif itself is a small library. dav1d is already in KaOS.

So if you add one package (libavif built with dav1d support), plug-in in kimageformats will have read-only AVIF support easily.

AVIF test files:
https://github.com/AOMediaCodec/av1-avif/tree/master/testFiles

**Comment by demmm** [comment]
Thanks for the detailed description, implemented.
