### ISSUE TITLE
QGit 2.10 packaging has out-of-sync md5sum (and and unused obsolete patch)

### ISSUE THREAD

**Issue by hartwork** [KaOSx/apps#206]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

qgit 2.10

#### Used repositories

> …

#### Expected behaviour

> …

#### Actual behaviour

Two issues:
- (Patch `7b8f1ff9ce16bc2d8457362df2017bc0ffe65458.diff` is not used and is already [included in QGit 2.10 upstream](https://github.com/tibirna/qgit/commit/7b8f1ff9ce16bc2d8457362df2017bc0ffe65458).)
- Because of an [upstream Git tag move](https://github.com/tibirna/qgit/pull/123#issuecomment-1010183267), MD5 checksum `0bbc4308cc5c366964ff9f8d77aca6a8`  is no longer correct for file `qgit-2.10.tar.gz`. The new MD5 sum is `f8aaff63dfcf963fa1bd6d5211a8eacd`, see below for proof.

```console
# wget https://github.com/tibirna/qgit/archive/qgit-2.10.tar.gz
# md5sum qgit-2.10.tar.gz 
f8aaff63dfcf963fa1bd6d5211a8eacd  qgit-2.10.tar.gz
```

CC @demmm @tibirna

#### Steps to reproduce the problem

> …

#### System info link created by Octopi > Tools > SysInfo

> …

**Comment by demmm** [comment]
As for the first issue, patch has not been in use since 2018, commented out see https://github.com/KaOSx/apps/blob/master/qgit/PKGBUILD#L19
