### ISSUE TITLE
No login kde plasma sound after upgrade to 5.24.0

### ISSUE THREAD

**Issue by constantius24** [KaOSx/apps#208]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> …

#### Used repositories

> …

#### Expected behaviour

> …

#### Actual behaviour

> …

#### Steps to reproduce the problem

> …

#### System info link created by Octopi > Tools > SysInfo

> …

**Comment by demmm** [comment]
Make sure to provide actual information as asked, nothing can be done with what is given now. At least provide the SysInfo.

**Comment by demmm** [comment]
Not sure if you are reporting a login sound or a general login issue, but if it is about sound, then it is an upstream issue:
https://bugs.kde.org/show_bug.cgi?id=449828

**Comment by demmm** [comment]
This report will stay open until upstream has the needed fix/patch, easier to track that way.

**Comment by demmm** [comment]
Issue is now fixed upstream, closing.
