### ISSUE TITLE
renamed source of inxi ?

### ISSUE THREAD

**Issue by ShalokShalom** [KaOSx/apps#21]
Inxi fails to build here and the correct source seems to use inxi_ instead inxi- https://code.google.com/p/inxi/source/browse/tarballs/

**Comment by demmm** [comment]
Editing a PKGBUILD to change an underscore to a hyphen for a source (inxi in this case) that constantly renames itself is not an apps issue, it is part of packaging.
Closing

**Comment by ShalokShalom** [comment]
Yes, i just want to make you aware about this change.
