### ISSUE TITLE
Konqueror has freenode bookmarked

### ISSUE THREAD

**Issue by ShalokShalom** [KaOSx/apps#210]
The current Konqueror build provides a link to the old channel on freenode in the bookmarks toolbar. 
I had a look in its PKGBUILD to fix this, and it seems to be configured elsewhere.

**Comment by demmm** [comment]
KaOS does not maintain konqueror code, so not a KaOS or packaging issue.

**Comment by demmm** [comment]
Re-opening, part of outdated ISO settings.
