### ISSUE TITLE
Package telepathy-qt5 missing

### ISSUE THREAD

**Issue by preeder** [KaOSx/apps#213]
#### Submission type

  - [X] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> telepathy-morse, telepathy-logger-qt5

#### Used repositories

> apps

#### Expected behaviour

> Ability to install via pacman -S

#### Actual behaviour

> Fails due to broken dependency to telepathy-qt5

#### Steps to reproduce the problem

> pacman -S telepathy-logger-qt5

#### System info link created by Octopi > Tools > SysInfo

> …

**Comment by demmm** [comment]
Not a bug, the whole KTP/telepathy stack is removed:
https://forum.kaosx.us/d/3029-replacing-kde-telepathy
