### ISSUE TITLE
The Windows Switcher installation is broken, resources are missing

### ISSUE THREAD

**Issue by ArrayBolt3** [KaOSx/apps#219]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> kwin6

#### Used repositories

kde-next, build, core, main, apps

#### Expected behaviour

Pressing Alt+Tab should reveal the task switcher as you flip through the stack of open windows.

#### Actual behaviour

No task switcher is shown, and an alert from "kdialog" appears with the text `The Window Switcher installation is broken, resources are missing. Contact your distribution about this.`

#### Steps to reproduce the problem

1. Open at least two windows.
2. Press Alt+Tab.

#### System info link created by Octopi > Tools > SysInfo

https://dpaste.com/8KNUFMBWN

**Comment by demmm** [comment]
Since I cannot reproduce on 2 systems (Alt-Tab just works) and an important part of the SysInfo is left empty (pacman.log is the most important for this), make sure to post your `/var/log/pacman.log`

**Comment by marco-parillo** [comment]
I have the same symptom, and other than the message, alt-tab seems to work fine for me. Anyway, my full pacman log is: https://raw.githubusercontent.com/marco-parillo/KaOS-Notes/main/pacman.log

**Comment by demmm** [comment]
On startup, it just worked, now with many windows open, I see the same, have either of you looked at the upstream bug reports for this already?

**Comment by demmm** [comment]
It looks to be this file that is not loading https://invent.kde.org/plasma/kwin/-/blob/master/src/tabbox/switchers/thumbnail_grid/contents/ui/main.qml?ref_type=heads

**Comment by ArrayBolt3** [comment]
I think it's a problem with the Midna theme based on log output:

```
Dec 24 12:19:35 user-optiplex9020 kwin_wayland[1712]: kwin_tabbox: Component failed to load:  QList(file:///usr/share/plasma/look-and-feel/org.kde.midna.desktop/contents/windowswitcher/WindowSwitcher.qml:94:29: PlasmaCore.IconItem >
                                                                                      PlasmaCore.IconItem {
                                                                                      ^)
```

See https://invent.kde.org/plasma/plasma-workspace/-/issues/82

**Comment by ArrayBolt3** [comment]
Assuming this is how it's supposed to look, I think I fixed it.

![image](https://github.com/KaOSx/apps/assets/104878738/73fc494b-abd9-4d85-9a59-ac9271fe65f7)

Here's the diff:

[window_switcher_fix.txt](https://github.com/KaOSx/apps/files/13762596/window_switcher_fix.txt)

**Comment by demmm** [comment]
https://github.com/KaOSx/midna/commit/c279c1950c78a4e66fc305fc6e72983d823f708f  should fix this issue
No longer use separate theme files for desktop & window switchers, just use the upstream (moved to a lib) settings.
