### ISSUE TITLE
K3b - burning to dvd - hangs on preparing files

### ISSUE THREAD

**Issue by quietpinguin** [KaOSx/apps#22]
Hi

K3b (Version 2.9.90) is installed from KaOS apps using Octopi on installation of KaOS ISO 2015.04

Starting K3b - a new DVD Video project is selected. Files are dragged into the current project.

On selecting start (to burn) , k3b hangs when trying to prepare data.

(It should be noted the the file permissions for cdrdao and cdrecord are OK. Package dvd+rw is installed. User is assigned to "optical" group. )

Any ideas?

**Comment by demmm** [comment]
k3b packaging has been completely adjusted.  Is this bug fixed now?
All tests here show burning works fully again.

**Comment by demmm** [comment]
Seems fixed, no further response.
