### ISSUE TITLE
Dolphin not showing panels when minimize and restore the window, under X11!

### ISSUE THREAD

**Issue by gilbertoferreira** [KaOSx/apps#223]
#### Submission type

  - [ X] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> KDE Plasma 6 Dolpgin 

#### Used repositories

> pacman

#### Expected behaviour

>Not hide the panels when minimize and restore the window, under X11.

#### Actual behaviour

> When minimize and restore the window, under X11, the panels are gone!

#### Steps to reproduce the problem

> Install KaOS, using Plasma6 with X11 and the issue appears

#### System info link created by Octopi > Tools > SysInfo

> Operating System: KaOS (2024) 
KDE Plasma Version: 6.0.1
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.2
Kernel Version: 6.6.16-1 (64-bit)
Graphics Platform: X11
Processors: 4 × AMD A12-9720P RADEON R7, 12 COMPUTE CORES 4C+8G
Memory: 15.1 GiB of RAM
Graphics Processor: AMD Radeon R7 Graphics
Manufacturer: Acer
Product Name: Aspire A515-41G
System Version: V1.09

**Comment by demmm** [comment]
Upstream issue, not KaOS packaging:
https://bugs.kde.org/show_bug.cgi?id=481952
This upstream issue was known, but waiting for a bit more feedback before applying the linked patch, since it is not an issue on default for KaOS, Wayland, and no results yet about the impact on a Wayland session.

**Comment by gilbertoferreira** [comment]
> Upstream issue, not KaOS packaging: https://bugs.kde.org/show_bug.cgi?id=481952 This upstream issue was known, but waiting for a bit more feedback before applying the linked patch, since it is not an issue on default for KaOS, Wayland, and no results yet about the impact on a Wayland session.

It's an issue, because I dont use Wayland.
Do not force me to do that.
But anyway, never mind.
I already leave from Kaos.
Thanks.

**Comment by demmm** [comment]
Issue is not fixed, and will be fixed, once it is clear that upstream did not break the default session with the published commit.
