### ISSUE TITLE
Audacity install error

### ISSUE THREAD

**Issue by KardiWeb** [KaOSx/apps#23]
Hello!

resolving dependencies...
looking for conflicting packages...
Package (14) New Version Net Change Download Size
main/blas 3.5.0-1 0.36 MiB
main/lapack 3.5.0-1 15.19 MiB
main/libsoxr 0.1.1-1 0.34 MiB
main/lilv 0.20.0-2 0.58 MiB
main/lv2 1.10.0-1 0.87 MiB 0.14 MiB
main/python2-numpy 1.9.2-1 15.12 MiB
main/raptor 2.0.15-2 1.98 MiB
main/rasqal 0.9.33-1 1.71 MiB
main/redland 1.0.17-1 1.72 MiB
main/serd 0.20.0-1 0.19 MiB
main/sord 0.12.2-1 0.14 MiB
main/sratom 0.4.6-2 0.08 MiB
main/wxgtk2.9 3.0.2-1 28.35 MiB
apps/audacity 2.1.0-1 19.71 MiB
Total Download Size: 0.14 MiB
Total Installed Size: 86.33 MiB

:: Retrieving packages ...

warning: failed to retrieve some files 
Errors occurred, no packages were upgraded.

**Comment by demmm** [comment]
As always, check if your mirror is synced and update before installing ANY.
 Not a bug.
