### ISSUE TITLE
Firefox crashing

### ISSUE THREAD

**Issue by NoSavvy** [KaOSx/apps#232]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> …

#### Used repositories

> …

#### Expected behaviour

> …

#### Actual behaviour

> …

#### Steps to reproduce the problem

> …

#### System info link created by Octopi > Tools > SysInfo

> …

**Comment by demmm** [comment]
Duplicate of https://github.com/KaOSx/apps/issues/233
