### ISSUE TITLE
Dropbox dont sync on XFS

### ISSUE THREAD

**Issue by x11tete11x** [KaOSx/apps#24]
This is caussing me a lot of problems, then i remember that my Debian server has an ext4 partition with dropbox, after check that it's working good, so when i google Dropbox xfs, here is it:

https://www.dropboxforum.com/hc/communities/public/questions/203344435-Dropbox-on-XFS-bug-Wont-detect-new-files-to-upload-except-on-root-folder-

so default FS for KaOS it's XFS, i think it should be upgraded as soon possible thx!

**Comment by x11tete11x** [comment]
im testing dropbox 3.5.64 this issue is resolved and sync flawessly on XFS

**Comment by demmm** [comment]
Experimental build 3.5.65 is up, please confirm it is working correctly so it can move to all users asap:
sudo pacman -U http://kaosx.tk/repo/build/dropbox-3.5.65-1-x86_64.pkg.tar.xz

**Comment by x11tete11x** [comment]
Testing it right now, working good here, XFS upload and download sync works perfect (i made some test, modify files on my synced folder on XFS partition: OK , then erease and rename folders on Dropbox site, then my synced folder on XFS gets updated: OK) :D so, here is working :+1:

**Comment by demmm** [comment]
OK, will move it shortly, and will close once it is moved.
