### ISSUE TITLE
qbittorrent - status error

### ISSUE THREAD

**Issue by Copy001** [KaOSx/apps#26]
qbittorrent (version 3.2.0) was installed from KaOS apps with Octopi (ISO KaOS 2014.04)

Status don't refresh 
http://i.imgur.com/hsnHfci.png

But I grab the same version from http://www.qbittorrent.org/download.php and then I compiled it (follow the instructions on "readme" file; ./configure, make && make install), then qbittorrent was run as always http://i.imgur.com/gqVp19p.png but just a little changes on interface.

**Comment by demmm** [comment]
Can you run qbittorrent from cli (starting it by typing "qbittorrent" in a terminal?
Does it show any message on the hang?
Is your system fully updated?
Open octopi > Tools > SysInfo
Paste the gists link it produces here.

**Comment by Copy001** [comment]
Terminal:

service is "org.kde.StatusNotifierItem-1350-1"
Registering a client interface to the KStatusNotifierWatcher

Yes, except for kscreengenie is updated.

SysInfo: https://gist.github.com/anonymous/9882844956c42d3679ee

**Comment by demmm** [comment]
Where did you pacman -U covergloobus from?

**Comment by Copy001** [comment]
From here https://aur.archlinux.org/packages/covergloobus-bzr/

**Comment by demmm** [comment]
When you compiled your version, did you compile with Qt 4 or Qt 5?
KaOS uses Qt 5, that is why the better integration.
Looks like an upstream issue, when using Qt 5, though not present on earlier git builds, will switch back to a git build to see if that fixes this.

**Comment by demmm** [comment]
http://kaosx.tk/packages/index.php?act=show&subdir=build&sortby=date&file=qbittorrent-3.2.0.1-1-x86_64.pkg.tar.xz Seems to have fixed this issue, you can try and see by using pacman -U to install if you don't have the build repo enabled.

Issue will be closed once this 3.2.0.1 moves to [apps]
