### ISSUE TITLE
kmail error after Jul 03rd uprgrade

### ISSUE THREAD

**Issue by chirpi** [KaOSx/apps#27]
Hi Guys,

Looks like kmail is broken since the Jul 03rd (kde 15.04.3).  Every time I run kmail I get this error:

kmail: symbol lookup error: /usr/lib/libKF5CalendarUtils.so.5: undefined symbol: _ZN8KCalCore7Visitor5visitE14QSharedPointerINS_5EventEE

**Comment by demmm** [comment]
Thanks for reporting.  This is a known issue.  Unfortunately to fix, Frameworks 5.12.0 was needed.
Kmail in the [build] repo is fully working again (the whole pim stack build on 5.12.0), but can't move to all users until Frameworks 5.12 is fully released, will be this Friday.

**Comment by chirpi** [comment]
Thanks for the quick response.  I will test again after the Friday update.

**Comment by demmm** [comment]
Fixed Kmail is now moved, closing this issue.
