### ISSUE TITLE
masterpdfeditor.desktop file refers to incorrect executable path

### ISSUE THREAD

**Issue by JantarMantar** [KaOSx/apps#28]
It seems upstream has changed name of the binary executable starting with version 3. The new executable path is `/opt/masterpdfeditor/masterpdfeditor3`. The .desktop file that gets installed still refers to version 2 binary.

**Comment by demmm** [comment]
Thanks for reporting, issue is simpler to fix, will adjust .desktop to just use "pdfeditor, so this issue won't come up again.
You can run it now (as is in apps) with "pdfeditor" in a terminal.
Binary was already changed, .desktop did not have a number set either.
