### ISSUE TITLE
Dolphin free space not configured

### ISSUE THREAD

**Issue by DarkknightAK** [KaOSx/apps#29]
when make an left click on right buttom of dolphin where the free space is written you can open filelight, partition manager, ... but this modul isn't configured you only come to the webpage. but both apps are installed in the standard installation.

**Comment by demmm** [comment]
Not sure how the build can be adjusted for this, are you sure this is fully implemented upstream?
There are no indications during the build or CMakeLists how o connect to filelight for example.

**Comment by DarkknightAK** [comment]
I will ask.
