### ISSUE TITLE
image-exiftool files are installed in the wrong location

### ISSUE THREAD

**Issue by padhia** [KaOSx/apps#30]
The files are installed in /home/anke/ :)

**Comment by demmm** [comment]
No idea what happened, rebuild with exact same settings seems to fix it:
http://kaosx.tk/packages/pkg-ls.php?package=image-exiftool-10.00-2-x86_64.pkg.tar.xz&subdir=build
sudo pacman -U http://kaosx.tk/repo/build/image-exiftool-10.00-2-x86_64.pkg.tar.xz

**Comment by JantarMantar** [comment]
Yep, that fixed it. Thanks!

**Comment by padhia** [comment]
This one is back. For some reason, this package loves to reside in your home directory. :)

**Comment by padhia** [comment]
Thanks.
