### ISSUE TITLE
Google Chrome Crashes/System Hangs

### ISSUE THREAD

**Issue by mkchinniah** [KaOSx/apps#31]
I have installed the latest Kaos Version 1 Week back. Iam satisfied with your version, but frequently system hangs when using google chrome. I updated my system and chrome yesterday but still the problem persists. Please look into the issue. Thanks.

**Comment by demmm** [comment]
Info needed.
See http://kaosx.us/asking-and-reporting-the-smart-way/ to provide needed Sysinfo
Also provide appropriate logs for when the hang occurs.

**Comment by demmm** [comment]
No further response from submitter, closing
