### ISSUE TITLE
kmail - unable to send emails

### ISSUE THREAD

**Issue by blutus** [KaOSx/apps#32]
Hi,
Since the last application update (15.08) I have an issue sending emails. Every time I try to send email I get the following error.  Sorry I could not debug further as I can't find logs anywhere.

"Unable to transport message.  Failed to create SMTP Job"

Regards,
Aravind.

**Comment by demmm** [comment]
How often do you update and what "last" update are you referring too?  15.08 is an update from more then 6 weeks ago, 15.08.1 is now in the repos.

**Comment by blutus** [comment]
Packages are up to date.   Sorry I should have mentioned the problem started after 15.08 and still persists.  Last time around  . 1 fixed the kmail issue.  So I waited till  15.08.1  to see the issue was fixed before logging  ticket. 

Aravind

On 23/09/2015 11:10, demmm <notifications@github.com> wrote:

How often do you update and what "last" update are you referring too? 15.08 is an update from more then 6 weeks ago, 15.08.1 is now in the repos.

**Comment by demmm** [comment]
Upstream report with:
https://bugs.kde.org/show_bug.cgi?id=356075

**Comment by demmm** [comment]
Issue is fixed with https://github.com/KaOSx/apps/commit/900fa19421b81cf335181b286fbbdc829bfec86f
This report will be closed once new kdepimlibs moves to the [apps] repo

**Comment by blutus** [comment]
Thank you.  I will update the system and try

Aravind

On 9/04/2016 01:00, demmm <notifications@github.com> wrote:

Issue is fixed with 900fa19
This report will be closed once new kdepimlibs moves to the [apps] repo
