### ISSUE TITLE
gitter: Wrong categorie?

### ISSUE THREAD

**Issue by kaos-addict** [KaOSx/apps#35]
Not sure about but should'nt it be categorized in devlopment instead of utilities?

P.S: Not sure if it is the right place for that?

**Comment by demmm** [comment]
Development is really for applications actually used as such, qtcreator, kdevelop, scala are such apps.
Gitter is a utility to communicate, you can't develop anything with it.

**Comment by kaos-addict** [comment]
Hmm ok, now I know why :)

**Comment by demmm** [comment]
You want me to add the internet group?

**Comment by kaos-addict** [comment]
Don't know if it would fit better in internet or utilities, actually seeing this explanation, Utilities lokks quite ok...
