### ISSUE TITLE
Can't download google-chrome, Octopi.

### ISSUE THREAD

**Issue by jamesjsapp** [KaOSx/apps#39]
Installing selected packages...

resolving dependencies...
looking for conflicting packages...
Package (2) New Version Net Change Download Size
main/gconf 3.2.6-6 7.27 MiB
apps/google-chrome 49.0.2612.0-1 176.56 MiB 47.26 MiB
Total Download Size: 47.26 MiB
Total Installed Size: 183.83 MiB

:: Retrieving packages ...

warning: failed to retrieve some files 
Errors occurred, no packages were upgraded.

Command finished with errors!

**Comment by demmm** [comment]
Don't post snippets, post the full log, including the commands used.
In this case, to be able to give info, use pacman.
```
sudo pacman -Syu
```

**Comment by jamesjsapp** [comment]
prob. solved, Octopi sync did not show updates, thought system was updated
pacman pulled 8 updates including apps
google-chrome installed, thanks
