### ISSUE TITLE
Octopi md5sum issue after fresh install from USB.

### ISSUE THREAD

**Issue by smcdonough** [KaOSx/apps#40]
Checking core main apps... 

md5sum: /tmp/.1000mirrordb.tmp: No such file or directory
'core' is not synced. 
'main' is not synced. 
'apps' is not synced.  

Command finished OK!

**Comment by demmm** [comment]
your issue is probably:
http://kaosx.us/phpBB3/viewtopic.php?f=11&t=1334

**Comment by demmm** [comment]
No further response from submitter, assuming the forum post explained the needed action, closing.
