### ISSUE TITLE
Grass gis - missing GUI

### ISSUE THREAD

**Issue by p-neves** [KaOSx/apps#41]
Hi:

When I try to start Grass GIS (grass70), I get the following error:

ERROR: <wxpython> requested, but not available. Run GRASS in text mode (-text) or install missing package (usually 'grass-gui')

However I cannot find either grass-gui nor wxpython...

**Comment by demmm** [comment]
This is not a bug but intended behavior.
Grass is in the kaOS repos as a dependecy of Qgis, it is not here as a standalone GTK/wxpyython based GUI.
Use Grass in Qgis or in cli mode.  It will not enter the repo as a GTK based GUI.
