### ISSUE TITLE
No KMail in repository?

### ISSUE THREAD

**Issue by jlnostr** [KaOSx/apps#42]
Because Thunderbird looks like crap I want to install KMail. Unfortunately, it's not in the repositorys even if it's a KDE application. Maybe it's related to #38 :/
Anyway, it would be nice, if you could add KMail asap.

Greetings from Germany,
Julian

**Comment by demmm** [comment]
KDE does not release a package Kmail, see if you can find it:
http://download.kde.org/stable/

KaOS ships as upstream releases, so Kdepim is in the repos, which contains KMail.
See that FAQ and about pages on the KaOS website if you have questions about splitting and not splitting of packages here.
See the file listing under /usr/bin for kdepim:
http://kaosx.us/packages/pkg-ls.php?package=kdepim-15.12.2-1-x86_64.pkg.tar.xz&subdir=apps

**Comment by jlnostr** [comment]
Thanks, didn't know that KMail is in the `kdepim` package :)
