### ISSUE TITLE
Add support for pandoc and syncthing

### ISSUE THREAD

**Issue by jlnostr** [KaOSx/apps#43]
There are two tools I'm using a lot. `pandoc` and `syncthing`. Would be nice to find them in the repo, too :)

**Comment by demmm** [comment]
See the website what KaOS is and what it is not.
Missing packages are not bugs, but clearly explained.
To add packages to your install you would like to have, see:
http://kaosx.us/packaging-guide/

From the home page http://kaosx.us/:

>  ....There is no goal to make the most possible software available, KaOS will stay limited in size of the repositories, .....

**Comment by jlnostr** [comment]
Well, maybe I should read more carefully. Thanks anyway :)
