### ISSUE TITLE
Dolphin and Klauncher

### ISSUE THREAD

**Issue by joriant** [KaOSx/apps#48]
Hi,
Just installed KaOs (in French). Dolphin won't show any files and show this instead

Impossible de démarrer le processus Impossible de créer le module d'entrée / sortie :
klauncher a retourné : Erreur lors du chargement de « /usr/lib/qt5/plugins/kf5/kio/file.so »

Help appreciated.

Thanx

**Comment by demmm** [comment]
Make sure to never install any without fully updating the system, make sure to run "mirror-check" or open Octopi and see if your mirror is fully synced.
If synced, run "sudo pacman -Syu", this will be a large update, reboot after it is completed.

If you did update your install, then open Octopi > Tools > SysInfo and paste the link that produces

**Comment by demmm** [comment]
No further response from submitter
