### ISSUE TITLE
Can't change or create new Activities

### ISSUE THREAD

**Issue by sweaper** [KaOSx/apps#49]
I can't manage any Activities. But when I tried to manage the Activities via widget I got this error:

> Error loading QML file: file:///usr/share/plasma/plasmoids/org.kde.plasma.activitybar/contents/ui/main.qml:24:1: module "org.kde.activities" is not installed

I just installed this distro and did an upgraded with a restart.

**Comment by demmm** [comment]
Open Octopi > Tools > SysInfo and paste the link that will return

**Comment by sweaper** [comment]
https://gist.github.com/anonymous/4260383f2589bdbdc7af

**Comment by demmm** [comment]
You remove the needed parts of kactivities, how do you expect they can work then?
```
[2016-03-26 12:42] [PACMAN] Running 'pacman -R kactivitymanagerd kactivities'
'''

**Comment by sweaper** [comment]
I tried reinstalling these 2 packages, but didn't work. So I did a new clean installation of KaOS and updated it with a reboot. Still the same problem... but now making sure I still have those two packages https://gist.github.com/anonymous/7e29286b78863882dc74

**Comment by demmm** [comment]
OK, checked some more too.
Looks like this could be an upstream issue.  Kactivities was just split into kactivities, kactivitymanagerd and parts moved into kio-extras + plasma-workspace (Plasma 5.6.0 & frameworks 5.20.0).  It might be the activity applet was not updated for these changes.
Please run ```kactivitymanagerd status'```  to see if it running correctly

**Comment by sweaper** [comment]
Yes, it's running. 
> kactivitymanagerd status
> The service is running, version: 7.0.0
> Cleaning up...

**Comment by demmm** [comment]
Issue found, please test:
sudo pacman -U http://kaosx.tk/repo/build/kactivities-5.20.0-3-x86_64.pkg.tar.xz
and restart plasma (reboot, restart sddm or ```kquitapp5 plasmashell && plasmashell```)

**Comment by sweaper** [comment]
Spot-on!! Working nicely. GJ! :+1:

**Comment by demmm** [comment]
Thanks for checking, moving to all users now, closing.
