### ISSUE TITLE
Can't open firefox

### ISSUE THREAD

**Issue by dagodax** [KaOSx/apps#55]
[dago@kaos ~]$ firefox
XPCOMGlueLoad error for file /usr/lib/firefox/libxul.so:
libhunspell-1.3.so.0: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
[dago@kaos ~]$ 

I'm in build.

**Comment by KdeOs** [comment]
Yep, I know, huge rebuild needed for new hunspell.  Just use pacman -S
main/hunspell until all is done.
Sorry, missed new hunspell was a .so up


Anke Boersma
678-269-7436
www.veritasfarm.net

**Comment by demmm** [comment]
Yep, I know, huge rebuild needed for new hunspell.  Just use pacman -S main/hunspell until all is done.
Sorry, missed new hunspell was a .so up

**Comment by demmm** [comment]
Rebuild firefox is up, closing
