### ISSUE TITLE
mumble close main window when connect to server

### ISSUE THREAD

**Issue by dagodax** [KaOSx/apps#58]
It just leave space en systemtray without visible icon. That icon allows to close the app, but the main window is gone.
[dago@kaos ~]$ mumble
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-dago'
CELT bitstream 8000000b from /usr/lib/mumble/libcelt0.so.0.7.0
CELT bitstream 80000010 from /usr/lib/mumble/libcelt0.so.0.11.0
Theme: "Mumble"
Style: "Lite"
--> qss: ":builtin/themes/Mumble/Lite.qss"
Locale is "es_ES" (System: "es_ES")
TextToSpeech: Compiled without support for speech-dispatcher
Database SQLite: "3.12.2"
Overlay: Removing old socket on "/home/dago/.MumbleOverlayPipe"
Overlay: Listening on "/home/dago/.MumbleOverlayPipe"
Updating application palette
QObject::connect: No such slot Usage::reportJitter()
GlobalShortcutX: Using XI2 2.3
SocketRPC: Removing old socket on "/home/dago/.MumbleSocket"
AudioInput: 40000 bits/s, 48000 hz, 480 sample
PulseAudio: Starting input alsa_input.pci-0000_00_1b.0.analog-stereo
PulseAudio: Starting echo: alsa_output.pci-0000_00_1b.0.analog-stereo.monitor
PulseAudio: Starting output: alsa_output.pci-0000_00_1b.0.analog-stereo
AudioInput: Initialized mixer for 1 channel 44100 hz mic and 0 channel 48000 hz echo
AudioInput: Initialized mixer for 1 channel 44100 hz mic and 1 channel 44100 hz echo
AudioOutput: Initialized 2 channel 44100 hz mixer
warning: The VAD has been replaced by a hack pending a complete rewrite
AudioInput: ECHO CANCELLER ACTIVE
OpenSSL Support: 1 (OpenSSL 1.0.2g  1 Mar 2016)
ServerHandler: TLS cipher preference is "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
PulseAudio: Forcibly disconnected from PulseAudio
[dago@kaos ~]$

**Comment by demmm** [comment]
Please check Mumble 1.2.83 up in the build repo.

**Comment by dagodax** [comment]
It works fine. Thanks!

**Comment by demmm** [comment]
OK, moving to apps then and closing this now

**Comment by dagodax** [comment]
The issue is back. It works for one day, for me and another user, but now fail in the same way.

**Comment by demmm** [comment]
Make sure to clean the conf files in your home dir one time, seems settings have changed

**Comment by dagodax** [comment]
Conf files cleaned, the problem persists.

**Comment by demmm** [comment]
Certain servers only?  Tried some others?

**Comment by dagodax** [comment]
I tried one of each continent, same problem.

**Comment by demmm** [comment]
Checked upstream?  Nothing in the backtrace shows a reason why.

**Comment by demmm** [comment]
hmm, maybe it is new SQlite, mind getting a new .d for mumble?  remove ~/.local/share/Mumble/Mumble/mumble.sqlite

**Comment by forostm** [comment]
this issue is related to 
https://github.com/mumble-voip/mumble/issues/2192

test this patch: 
https://gist.github.com/forostm/79967fd973ae833bfc2ae2886d2947d2

**Comment by demmm** [comment]
patched mumble is up

**Comment by dagodax** [comment]
Now it's working fine. Thanks!
