### ISSUE TITLE
Faddo Mixer

### ISSUE THREAD

**Issue by Nithin-Reddy** [KaOSx/apps#59]
logginghandler: Could not communicate with the FFADO DBus service...

I always get this when ever I open this Faddo Mixer application.
Thank you.

**Comment by demmm** [comment]
The GUI depends on PyQt4, which will leave the repo soon, see:
https://kaosx.us/early-may-16-status/
libffado is rebuild with the GUI disabled, this issue will be closed once libffado moves to [main]

**Comment by demmm** [comment]
libffado rebuild is now in the [main] repo, closing
