### ISSUE TITLE
FatRat

### ISSUE THREAD

**Issue by Nithin-Reddy** [KaOSx/apps#60]
FatRat

While creating a 'New Torrent', There wasn't a way to add Web Url,
in Web Seeds Tab option.

Sorry for Posting this Issue here,

I don't known that there was seperate github page for this.

**Comment by demmm** [comment]
Is this a KaOS specific issue in FatRat?  Checked upstream if there is a similar report for it?

**Comment by demmm** [comment]
FatRat no longer has torrent support, incompatible with libtorrent-rasterbar version in KaOS.
It is in the repos as download manager.
Use any of the torrent specific apps (ktorrent, qbittorrent for example).
