### ISSUE TITLE
Okular

### ISSUE THREAD

**Issue by Nithin-Reddy** [KaOSx/apps#61]
Whenever a file is opened,
and selecting , Tools > 'Speak Whole Document' option from drop-down menu,
    OKULAR -> FREEZES.
and selecting , Tools > 'Speak Current Page' option from drop-down menu,
    OKULAR -> CRASHES.
Thank You.

**Comment by demmm** [comment]
Okular is rebuild without qtspeech.  This option is too soon to add, will be tried again once qtspeech becomes part of the regular stable Qt releases, might be with Qt 5.7.
This issue will be closed once okular-16.03.71-3 moves to the [apps] repo.

**Comment by demmm** [comment]
Moved to [apps], closing

**Comment by demmm** [comment]
See https://github.com/KaOSx/apps/issues/63
This is also a .desktop issue in Calligra
