### ISSUE TITLE
Opening BrainDump makes panel Freeze

### ISSUE THREAD

**Issue by Nithin-Reddy** [KaOSx/apps#63]
I have opened 'Briandump' from office option, in dock.
Once or while it is opened, my panel isn't working.
All other things seems to be working normal, like alt+tab...
My Panel is working, once 'Braindump' application is closed.

I get this error, after 'BrainDump is closed' 
                        KDEInit could not launch '/usr/bin/braindump'

**Comment by demmm** [comment]
These are all upstream Calligra issues (and reported to them a few times already).  The .desktop files are not ported to kf5 correctly yet.
I will leave this report and https://github.com/KaOSx/apps/issues/62 open for now, but nothing KaOS can do, it needs to be fixed upstream.
For braindump, a workaround is to either use from krunner, or edit the .desktop:
```kdesu kate /usr/share/applications/braindump.desktop'''
and comment out/remove line 84, make it look like this:
```#X-DBUS-StartupType=multi```

**Comment by demmm** [comment]
A workaround is now added in Calligra for the braindump.desktop, issue will be closed once moved to the [apps] repo
