### ISSUE TITLE
kaffeine 2.0.2-1 has no information in program guide

### ISSUE THREAD

**Issue by rolfep** [KaOSx/apps#65]
I use kaffeine to record OTA ATSC television with hdhomeruntc_atsc dual tuner that is LAN-connected.
I've installed KaOS 2016.04 to a new HTPC candidate built of Asus Z170I board with Skylake i5-6500 CPU as my new hardware needs a new kernel and I saw reports that KaOS works with this.  Mostly, this is a success story with some further challenges, such that kaffeine-2 does not display the channel guide information; it is blank:  Television > Program Guide.

On another machine on the LAN, I'm using the same HDHomerun tuner with kaffeine-1.2.2-6.mga5 (Mageia 5) and have been using the legacy kaffeine for two years without such a problem.  Although that machine has i7-2600K CPU @ 3.40GHz with 8 threads, it looks like kaffeine-1.2.2 is using only about 5% cpu, even when displaying a channel.  On the i5-6500, 4 cores @ 3.20GHz, kaffeine-2 uses more than one core, more than 100% cpu, if kaffeine is even open, no channel playing.

I understand legacy kaffeine is abandoned and I hope the new kaffeine will improve.  Thanks.

**Comment by demmm** [comment]
Kaffeine port to kf5 is very active at the moment, many bug reports are filed, an fixed fast upstream.  This is not a KaOS issue, nothing can be done here (not a packaging issue).
Best follow upstream reports and/or try kaffeine 2.0.3
It is currently in the [build] repo, will move to all users soon.

https://bugs.kde.org/buglist.cgi?component=general&list_id=1363364&product=kaffeine&resolution=---

**Comment by rolfep** [comment]
On 06/12/2016 04:01 PM, demmm wrote:
>
> Kaffeine port to kf5 is very active at the moment, many bug reports 
> are filed, an fixed fast upstream. This is not a KaOS issue, nothing 
> can be done here (not a packaging issue).
> Best follow upstream reports and/or try kaffeine 2.0.3
> It is currently in the [build] repo, will move to all users soon.
>
> https://bugs.kde.org/buglist.cgi?component=general&list_id=1363364&product=kaffeine&resolution=---
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/KaOSx/apps/issues/65#issuecomment-225465747>, or 
> mute the thread 
> <https://github.com/notifications/unsubscribe/AHedtf48btp-eFRg-RxTNpG_BiOP1On_ks5qLI-wgaJpZM4Iz57R>.
>
Ok, hope email reply works, thanks.

**Comment by demmm** [comment]
Checked kaffeine 2.0.5?  Still an issue with that version?

**Comment by demmm** [comment]
No further response from submitter.
