### ISSUE TITLE
Kaffeine fails to play audio cd

### ISSUE THREAD

**Issue by ShalokShalom** [KaOSx/apps#66]
VLC works, Kaffeine simply shows an empty screen. It reads the disk (i can hear the access) and stops then. See the difference between Screenshot 2 and 3 in the Play/Stop Panel:

![screenshot_27062016_105525](https://cloud.githubusercontent.com/assets/6344099/16374218/c8d3a210-3c55-11e6-838e-69f6093da314.png)

Kaffeine start, read the disk:

![screenshot_27062016_105553](https://cloud.githubusercontent.com/assets/6344099/16374214/c759f1f0-3c55-11e6-90fb-4d8184a82abe.png)

Kaffeine fails to play the disk:

![screenshot_27062016_105710](https://cloud.githubusercontent.com/assets/6344099/16374268/06cc9d92-3c56-11e6-8153-264de9998aca.png)

**Comment by demmm** [comment]
Checked upstream bug reports for this?  Kaffeine is currently very active developed/ported to kf5, might be a known issue regression already.

**Comment by demmm** [comment]
Actually, this is a known upstream bug:
https://bugs.kde.org/show_bug.cgi?id=364225

**Comment by demmm** [comment]
Checked kaffeine 2.0.5?  Still an issue with that version?

**Comment by demmm** [comment]
No further response from submitter.
