### ISSUE TITLE
the package ack 2.14-2  is installed in /home/...

### ISSUE THREAD

**Issue by forostm** [KaOSx/apps#68]
#### Submission type

  - [X ] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> ack 2.14-2

#### Used repositories

> core, main, apps

#### Steps to reproduce the problem

> the package ack 2.14-2  is installed in /home/...

**Comment by demmm** [comment]
Thanks for reporting, same perl build issue on the build server.....
Rebuild will be shortly (on gcc5), bug report will have to stay open until gcc 5 moves.

**Comment by demmm** [comment]
Fixed ack is up.
Should be fine to use with pacman -U:
```
sudo pacman -U http://kaosx.tk/repo/build/ack-2.14-3-x86_64.pkg.tar.xz
```
