### ISSUE TITLE
KCP

### ISSUE THREAD

**Issue by Nithin-Reddy** [KaOSx/apps#69]
#### Submission type

  - [x] Bug report

#### Expected behaviour

> …To Download files, when command is pasted in console

#### Actual behaviour

> … Package not found!

#### Steps to reproduce the problem

> …Go to: [http://kaos-community-packages.github.io/](url)
   ... Then click any one of package name available, then a pop-up menu will appear, select "copy command" option and paste it in terminal and press enter

#### System info link created by Octopi > Tools > SysInfo

> … https://gist.github.com/anonymous/12c09c90a2f1583948cdb26ecca627a5

**Comment by demmm** [comment]
This is not a KCP (kcp application) issue, but the website frontend used.  This is not maintained by KaOS, but issues go to:
https://github.com/KaOS-Community-Packages/KaOS-Community-Packages.github.io
