### ISSUE TITLE
Battery Status Error

### ISSUE THREAD

**Issue by ghost** [KaOSx/apps#70]
#### Submission type
- [ X] Bug report
#### Package name & version you are having issues with or have a request for

> … Unknown
#### Used repositories

> …Kaos
#### Expected behaviour

> …Show my Battery Status
#### Actual behaviour

> …It isn't showing up my battery status, It shows that I don't have a Battery, but I'm running it on my laptop, where my power-cord isn't plugged in, This doesn't happen each and every time, but it happens some-times, when I switch-on my laptop, If I restart my laptop, it would show my battery back, as far as my knowledge, I have experienced this problem only in KaOs. I haven't experienced this issue in Kubuntu.
#### Steps to reproduce the problem

> …It doesn't happen each and every time, It do occur in rare-cases
#### System info link created by Octopi > Tools > SysInfo

> …https://gist.github.com/anonymous/12c09c90a2f1583948cdb26ecca627a5
#### Images

> .... 
> ![screenshot-1](https://cloud.githubusercontent.com/assets/19215729/16752061/f149afb2-47fb-11e6-89eb-707cba55ed6b.png)
> ![screenshot-2](https://cloud.githubusercontent.com/assets/19215729/16752062/f19277e2-47fb-11e6-9f9a-82245fa6ccd0.png)

**Comment by Nithin-Reddy** [comment]
Here is another one, Where I met with this problem once again,

![screenshot-3](https://cloud.githubusercontent.com/assets/19215729/16798880/ce3dfc7e-490b-11e6-9b90-ad040f31737a.png)

**Comment by demmm** [comment]
Upstream, known issue:
https://bugs.kde.org/show_bug.cgi?id=350365

This report will stay open here as a reference point.

**Comment by demmm** [comment]
Now tracked in https://bugs.kde.org/show_bug.cgi?id=422111

**Comment by demmm** [comment]
As per above linked bug report, issue has been fixed in 2022, closing.
