### ISSUE TITLE
Eclipse needs JDK/OpenJDK 8

### ISSUE THREAD

**Issue by ShalokShalom** [KaOSx/apps#71]
#### Submission type
- [x] Bug report
#### Package name & version you are having issues with or have a request for

> … jdk 8.92-1
#### Used repositories

> … core, main, apps
#### Expected behaviour

> … eclipse starts, java starts from commandline
#### Actual behaviour

> … eclipse fails to start with this error: http://funkyimg.com/i/2ekaD.png
>         java fails to start from commandline with the error "file or directory not found"
#### Steps to reproduce the problem

> … Install jdk and eclipse, uninstall openjdk
>         Run 'java' in commandline
>         Run Eclipse
#### System info link created by Octopi > Tools > SysInfo

> … https://gist.github.com/3e5c182acf72a3afa09c1c6b0a440315

**Comment by demmm** [comment]
To use jdk, edit  /usr/share/eclipse/eclipse.ini
Current:
```
-startup
plugins/org.eclipse.equinox.launcher_1.3.200.v20160318-1642.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.400.v20160518-1444
-showsplash
org.eclipse.platform
--launcher.defaultAction
openFile
--launcher.appendVmargs
-vmargs
-Dosgi.requiredJavaVersion=1.8
-Xms256m
-Xmx1024m
```
Add 2 lines before  -vmargs
```
-vm
/opt/java/bin/java
```
So it will look like:
```
-startup
plugins/org.eclipse.equinox.launcher_1.3.200.v20160318-1642.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.400.v20160518-1444
-showsplash
org.eclipse.platform
--launcher.defaultAction
openFile
-vm
/opt/java/bin/java
--launcher.appendVmargs
-vmargs
-Dosgi.requiredJavaVersion=1.8
-Xms256m
-Xmx1024m
```

**Comment by demmm** [comment]
This report  has a wrong title, JDK is not installed in the /usr/bin/path, but is in /opt.

Bug though is in Eclipse requiring jdk/openjdk 8 version.
Current is packaged for regular java path as is set in Openjdk.  Openjdk version is at 7 though, so no longer suitable for Eclipse.

JDK certainly has a working java version:
```
/opt/java/bin/java -version
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
```

**Comment by ShalokShalom** [comment]
You state "Add 2 lines before -vmargs" and your example is different:

-vm
/opt/java/bin/java
--launcher.appendVmargs

Anyway, both dont work. I open kdesu kate /usr/share/eclipse/eclipse.ini
and edit the file is both ways, before --launcher.appendVmargs as well as before
-vmargs and save, still the same issue.

![screenshot_20072016_074557](https://cloud.githubusercontent.com/assets/6344099/16976360/840ef566-4e4e-11e6-81b7-80771078910a.png)

**Comment by demmm** [comment]
Run ```/opt/java/bin/java -version```

**Comment by ShalokShalom** [comment]
I run that command and get file not found, i reinstall jdk then and voila: Works.

Both places to fill in the 2 lines are fine.

**Comment by ShalokShalom** [comment]
Is there a solution yet? Can i close this?

**Comment by demmm** [comment]
Openjdk has moved to 8, once all tested and moved to the [main], this report will be closed.
Also will be the end of JDK in the KaOS repos, it is no longer legal to provide in a repository.  Available in KCP though.

**Comment by ShalokShalom** [comment]
When i try to start Mediathek View: https://gist.github.com/ShalokShalom/a04ca0d6ca8e088cd7c19ba9ae74a169
