### ISSUE TITLE
Unable to generate a SysInfo Link

### ISSUE THREAD

**Issue by Nithin-Reddy** [KaOSx/apps#72]
#### Submission type

  - [X ] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> …Octopi

#### Used repositories

> …KaOs

#### Expected behaviour

> …to give Output of my 'System Info'

#### Actual behaviour

> …I get this Error:
Error: "\xE2" on US-ASCII

#### Steps to reproduce the problem

> … Open Octopi and then select 

> sys-info option from dropdown menu of tools.

 

#### System info link created by Octopi > Tools > SysInfo

> …I'm Unable to create SysInfo Link..

I have Updated my System to latest version available.

This isn't a fresh install.

This is the old-link which I have of my SysInfo, (If useful)
[https://gist.github.com/anonymous/12c09c90a2f1583948cdb26ecca627a5](url)

Thank You.

**Comment by demmm** [comment]
Run Octopi from cli, then try again, see if you get some useful info.
There is some log on your system that has an unsupported character

**Comment by demmm** [comment]
No further response from submitter, closing
