### ISSUE TITLE
kmymoney-4.100.7-9 OFX Import dialog does nothing

### ISSUE THREAD

**Issue by padhia** [KaOSx/apps#75]
#### Submission type

  - [ X] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> …
kmymoney-4.100.7-9

#### Used repositories

> …
core,main,apps

#### Expected behaviour

> A valid OFX file should be imported and invalid file should display error messages

#### Actual behaviour

> Dialog closes with no action

#### Steps to reproduce the problem

> Select File->Import->OFX... and select a valid OFX file

#### System info link created by Octopi > Tools > SysInfo

> https://gist.github.com/0622c36e212c840efda8b36a983a8d92

#### Additional info
I have submitted a bug report to upstream: https://bugs.kde.org/show_bug.cgi?id=366492

I recompiled `kmymoney` using the github commit used in `4.100.7-8 PKGBUILD` and it has restored the functionality.

**Comment by demmm** [comment]
Please test latest checkout build:
```
sudo pacman -U http://kaosx.tk/repo/build/kmymoney-4.100.7-10-x86_64.pkg.tar.xz
```
if this fixes, then will be moved to all users right away.

**Comment by padhia** [comment]
Yes. That fixed the issue. Thank you.

**Comment by padhia** [comment]
I am sorry. My mistake in testing. The issue is still present. I accidentally tested the version I built using the  4.100.7-8 PKGBUILD which I knew works. I retested from the build repo that you uploaded today and the issue is still present. Sorry again for reporting incorrectly in haste.

**Comment by demmm** [comment]
I will wait 2-3 more days on some response to the bug report, otherwise will go back to compiling commit  4604c7eca3bc50902a60fdbfe95ee47482f487c8

**Comment by demmm** [comment]
Rebuild to last working commit is up in the apps repo, closing & waiting for upstream to address issues before moving to newer checkout.
