### ISSUE TITLE
Kaptan cuts text in german translation

### ISSUE THREAD

**Issue by ShalokShalom** [KaOSx/apps#78]
#### Submission type

  - [ x] Bug report

#### Package name & version you are having issues with or have a request for

> Kaptan 5.3-1

#### Used repositories

> core, main, apps

#### Expected behaviour

> Kaptan shows full text in clicking behaviour at german

#### Actual behaviour

> Kaptan cuts the test of clicking behaviour at german

#### Steps to reproduce the problem

> Open Kaptan in german via `LC_ALL=de_DE.UTF-8 kaptan`

#### System info link created by Octopi > Tools > SysInfo

> https://gist.github.com/anonymous/f183b2040cb8add8bf4e961afcef1ff7

**Comment by demmm** [comment]
You have access to transifex, German translations will need to be adjusted to fit the frame, shorten words, use abreviations, or leave words out (use just "files" for example instead of files & folders).

**Comment by demmm** [comment]
Fixed in updated translations
