### ISSUE TITLE
Add Look & Feel section to Kaptan

### ISSUE THREAD

**Issue by ShalokShalom** [KaOSx/apps#79]
#### Submission type

  - [x] Feature Request

#### Package name & version you are having issues with or have a request for

> … Kaptan 5.3-1

#### Used repositories

> … core, main, apps

#### Expected behaviour

> … I am able to select Look and Feel packages

#### Actual behaviour

> … I  am not able to select Look and Feel packages

#### Steps to reproduce the problem

> … Open Kaptan, move to the workspace page.

**Comment by demmm** [comment]
Won't be implemented.
Kaptan will stay limited, just gives a small overview what INDIVIDUAL components can be adjusted.  Last page offers the option to open systemsettings so users can explore all options.
