### ISSUE TITLE
Quassel client won't connect to its core after Qt 5.6 upgrade

### ISSUE THREAD

**Issue by Israphel** [KaOSx/apps#80]
#### Submission type

  - [ ] Bug report

#### Package name & version you are having issues with or have a request for

> quassel 0.12.4-3

#### Expected behaviour

> Connect to quassel-core (already running and configured) and load chat list.

#### Actual behaviour

> Quassel-client GUI is broken and doesn't connect

#### Steps to reproduce the problem

> Run quassel-core with systemd, either with sqlite or postgresql. Then launch the client and connect to your core (in my case, localhost).
Quassel-client on KaOS breaks: There's no left sidebar and doesn't load a thing.
Quassel-client (both Qt4 and Qt5, with and without KDE) on Ubuntu, Debian and Fedora works OK (same quassel-core still on KaOS, that doesn't change).

![screenshot_20160323_223902](https://cloud.githubusercontent.com/assets/720191/18017025/c5d4e720-6ba5-11e6-8679-cbee7fff00af.png)
![screenshot_20160323_223847](https://cloud.githubusercontent.com/assets/720191/18017024/c5d2ab4a-6ba5-11e6-8306-e438f6c7e7cb.png)

**Comment by demmm** [comment]
Two things, one localhost and 0.0.0. are not compatible, please show your /usr/lib/systemd/system/quassel.service
and 
/etc/conf.d/quassel
Second, if client GUI is off, did you try with a new/different user?

**Comment by Israphel** [comment]
and need listen=0.0.0.0 so I can connect from outside my home (like I'm doing at the moment). It is still localhost.

Service:
[Unit]
Description=Quassel core service
After=network.target

[Service]
Type=simple
User=quassel
Group=quassel
PIDFile=/var/run/quassel.pid
ExecStart=/usr/bin/quasselcore --listen=0.0.0.0 --configdir=/var/lib/quassel

[Install]
WantedBy=multi-user.target

/etc/conf.d/quassel
QUASSEL_USER=quassel
LISTEN=0.0.0.0

NOTE: I have been using that config since day 1, the Core always worked with the same user and the same certificate. My remote clients still works (all of them), only my kaos' client isn't working (since Qt 5.6 upgrade).
It says "connected", and if I want to reconnect it insists it's connected, but the GUI is half-way loaded.

**Comment by demmm** [comment]
Make sure to update, hopefully the force use of ssl will help here.
quassel 0.12.4-4 is in apps now (if your mirror is synced)

**Comment by Israphel** [comment]
Well, that did the trick. Not exactly sure what you did, but now the kaos client works and the xubuntu client still works as well.
