### ISSUE TITLE
ISO Writer open KFileDialog in /

### ISSUE THREAD

**Issue by ShalokShalom** [KaOSx/apps#81]
#### Submission type

  - [ x] Bug report

#### Package name & version you are having issues with or have a request for

> … ISO Writer 1.0.2-1

#### Used repositories

> … core, main, app

#### Expected behaviour

> … ISO Writer open KFileDialog in /home

#### Actual behaviour

> … ISO Writer open KFileDialog in /

**Comment by demmm** [comment]
Running from the menu, or starting from CLI with "IsoWriter".  Latter opens in ~/Downloads.
There is also the option to right click an ISO file > Actions > write to USB using isowriter.

Will check of the code or .desktop can be adjusted to have the menu item start in the Download directory too.

**Comment by demmm** [comment]
Open /usr/share/applications/isowriter.desktop and comment out/remove ```X-KDE-SubstituteUID=true```
That should fix, let me know if that fixes it for you, then it will be applied to the packaging.
