### ISSUE TITLE
"Mozc" - a Japanese Input Method Editor

### ISSUE THREAD

**Issue by wadaki** [KaOSx/apps#83]
#### Submission type
  - [ ] Bug report
  - [X] Feature Request

#### Package name & version you are having issues with or have a request for
"Mozc" - is a Japanese Input Method Editor and works with "ibus" and "fcitx"

#### Used repositories
See mozc's official "LinuxBuildInstructions".
http://www.geocities.jp/ep3797/mozc_01.html

#### Expected behaviour
Would be lovely to see in KaOS

**Comment by demmm** [comment]
fcitx-mozc was in the repos, but had to be removed with the end of Qt 4.
https://github.com/KaOSx/apps/blob/master/fcitx-mozc/PKGBUILD

It is now close to being ported to Qt5:
https://github.com/google/mozc
See progress on this issue:
https://github.com/google/mozc/issues/327

Preference here would be to re-add fcitx-mozc.  Any advantages of mozc-ut over fcitx-mozc?

**Comment by demmm** [comment]
fcitx-mozc was ported to Qt5 and is back in the repos, closing request, since it is added.
