### ISSUE TITLE
Transcode for K3B

### ISSUE THREAD

**Issue by ShalokShalom** [KaOSx/apps#84]
#### Submission type

  - [x ] Bug report
  - [ x] Feature Request

#### Package name & version you are having issues with or have a request for

> … Transcode https://bitbucket.org/achurch_/transcode/wiki/Home

![screenshot_20160923_115839](https://cloud.githubusercontent.com/assets/6344099/18784961/2e3e63be-8185-11e6-9d68-e924588f993f.png)

**Comment by ShalokShalom** [comment]
I adjust the PKGBUILD from Arch and it works: 
![screenshot_20160923_122531](https://cloud.githubusercontent.com/assets/6344099/18785668/0ea2872a-8189-11e6-9141-d957fb24ae6c.png)

**Comment by demmm** [comment]
Transcode is dead, not maintained for over 4 years, has multiple CVEs, does not build without using numerous patches, thus has been removed from opdepends of k3b and removed from kaOS repositories.
Use another application for ripping, until k3b starts using an actual maintained and buildable ripper.

**Comment by ShalokShalom** [comment]
I am writing the issue report for K3B, using your arguments. dvdbackup is very old as well, is there any alternative you know about, which is currently maintained, in order to recommend it to the K3B dev?
