### ISSUE TITLE
autologin & Numlock

### ISSUE THREAD

**Issue by goodluckclever** [KaOSx/apps#86]
#### Submission type

  - Feature Request

#### Package name & version you are having issues with or have a request for

> sddm.conf

#### Expected behaviour

> How can I not only enable autologin but also activate Numlock on Bootup?

#### Actual behaviour

> As is written in the comment: Currently ignored if autologin is enabled.

I'm looking forward to your reply. Thanks!

**Comment by demmm** [comment]
Did you check upstream if there are bug reports open for this?  KaOS ships the upstream sddm.conf with only adjustments made for used theme.  Numlock is not a feature added or adjusted by KaOS, purely SDDM code.

**Comment by demmm** [comment]
Actually, from your report it is not clear if even tried to edit /etc/sddm.conf to enable.....

**Comment by goodluckclever** [comment]
@demmm I'm afraid I've asked a wrong question. I'm sorry to trouble you. Anyway, thank you for your reply.

**Comment by demmm** [comment]
Closing this issue then.
Please reopen if you tested and find the feature should be working and is a KaOS only issue.
