### ISSUE TITLE
Cantata offers server setup as default

### ISSUE THREAD

**Issue by ShalokShalom** [KaOSx/apps#90]
Previous versions of Cantata preselect the option for single users, while the current one assume that the option, which requires an dedicated server instance of mpd. 

![screenshot_20170108_083632](https://cloud.githubusercontent.com/assets/6344099/21748160/b8683a50-d57d-11e6-8fe9-277088e0a6f4.png)

**Comment by demmm** [comment]
The upstream defaults have been used in KaOS as long as it has been in the repos.

**Comment by ShalokShalom** [comment]
No, you set that in the past to single user, after a request from me :/

**Comment by demmm** [comment]
Again, Cantata never shipped in KaOS with anything else but upstream defaults for this.
