### ISSUE TITLE
Mixxx fails to setup output devices

### ISSUE THREAD

**Issue by ShalokShalom** [KaOSx/apps#91]
#### Submission type

  - [x] Bug Report

#### Package name & version you are having issues with or have a request for

> … Mixxx 2.0.0-7

#### Used repositories

> … core main apps

#### Actual behaviour

> … 
![screenshot_20170108_110452](https://cloud.githubusercontent.com/assets/6344099/21748940/8bcebaae-d592-11e6-8a55-ccdf1fc2be76.png)

Here is the full log:

https://paste.kde.org/pu1zijqsf

#### Steps to reproduce the problem

> … Launch Mixxx, close it, reopen it. 
(The close was in my case a crash, which happened because i tried to load a file from another partition)

#### System info link created by Octopi > Tools > SysInfo

> … https://gist.github.com/anonymous/bdf2615b37998a5c47ef8de1412baa27

Audio works fine on Youtube, SMPlayer and Cantata. 

There are two sound devices on my Laptop, one build in, one connected via USB. Same issue happens, when i disconnect the USB device.

**Comment by demmm** [comment]
What happens if you assign the devices and close the app properly?

**Comment by ShalokShalom** [comment]
I cant assign them at all.

**Comment by demmm** [comment]
Remove the settings in your ~/.mixxx

**Comment by ShalokShalom** [comment]
Seems to work now, thanks
