### ISSUE TITLE
cinelerra package issues

### ISSUE THREAD

**Issue by keijukainen** [KaOSx/apps#94]
#### Submission type

  - [x ] Bug report

#### Package name & version you are having issues with or have a request for

> cinelerra

#### Used repositories

> kcp

#### System info link created by Octopi > Tools > SysInfo

> https://gist.github.com/anonymous/5bc28668c6544448af6b0c61b30de617

#### BUG REPORT

The cinelerra kcp package does not contain a complete .desktop file. It is missing the lines Icon=cinelerra and Categories=AudioVideo;

I couldn't find a cinelerra icon provided anywhere in the package so an icon needs to be manually added to the PKGBUILD. Feel free to use the image below.

https://s30.postimg.org/5jy0divlt/cinelerra.png

The strangest part of this package is that the cinelerra file in /usr/bin is actually a symlink... that points to a binary that doesn't exist. So it's not possible to actually run cinelerra with this package.

**Comment by demmm** [comment]
Cinelerra is not in the KaOS repos, or KaOS maintained.  Go to KCP for questions about KCP applications.
