### ISSUE TITLE
syslog-ng looking for conf in wrong location

### ISSUE THREAD

**Issue by RolandHughes** [KaOSx/apps#95]
#### Submission type

  - [ x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> syslog-ng

#### Used repositories

> abs/extra

#### Expected behaviour

> should successfully load at startup

#### Actual behaviour

> loads and fails

#### Steps to reproduce the problem

> build, install enable then start
[roland@i7-desktop abs]$ sudo systemctl list-units | grep -i syslog
Password: 
● syslog-ng.service                                                                                                     loaded failed failed    System Logger Daemon                                              

[syslog_notes.txt](https://github.com/KaOSx/apps/files/722055/syslog_notes.txt)

#### System info link created by Octopi > Tools > SysInfo

>https://gist.github.com/anonymous/bc89d3fd45fef9344a7786534f1fa369

**Comment by demmm** [comment]
KaOS is NOT based on any other distro.
syslog-ng is in the KaOS core repository.
