### ISSUE TITLE
wxgtk2.9 reporting as wrong version

### ISSUE THREAD

**Issue by RolandHughes** [KaOSx/apps#96]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> wxgtk2.9

#### Used repositories

> KaOS

#### Expected behaviour

> File should self identify as wxgtk2 but repo version information identifies the file as 3.02-4 which means the library module should identify as either wxgtk3 or wxgtk

#### Actual behaviour

> builds have to specifically reference wxgtk2 this is why boinc would neither build nor run

#### Steps to reproduce the problem

> install wxgtk2.9 from repo then try to build boinc from abs/community. The script has to be edited to identify wxgtk2.9. Neither wxgtk2 now wxgtk will locate the library. The other entries ending in 2 all get found

#### System info link created by Octopi > Tools > SysInfo

> https://gist.github.com/anonymous/bc89d3fd45fef9344a7786534f1fa369

**Comment by demmm** [comment]
Update your system before reporting, the package you report here is no longer in the KaOS repos.  If you had updated it would have been replaced.
