### ISSUE TITLE
org.freedesktop.NetworkManager.l2tp' was not installed

### ISSUE THREAD

**Issue by LinuxCuba** [KaOSx/apps#97]
#### Submission type

  - [X] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

kdeplasma-applets-networkmanagement

#### Expected behaviour

I made  an L2TP connection through kdeplasma-applets-networkmanagement, clicking on it and I get the error "Connection failed: The VPN service 'org.freedesktop.NetworkManager.l2tp' was not installed." Any other package besides "l2tp" needed to be installed? If not what's the problem?

#### Actual behaviour

> …

#### Steps to reproduce the problem

> …

#### System info link created by Octopi > Tools > SysInfo

> …

**Comment by demmm** [comment]
Looks like you will need networkmanager-pptp from the repo, and might need to add/build this one:
https://github.com/nm-l2tp/network-manager-l2tp

**Comment by LinuxCuba** [comment]
I am install networkmanager-pptp networkmanager-qt networkmanager-vpnc networkmanager-openvpn and networkmanager, clone git repo
[linuxcuba@SeguRed tmp]$ git clone https://github.com/nm-l2tp/network-manager-l2tp
Cloning into 'network-manager-l2tp'...
remote: Counting objects: 1814, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 1814 (delta 0), reused 0 (delta 0), pack-reused 1810
Receiving objects: 100% (1814/1814), 1.33 MiB | 14.00 KiB/s, done.
Resolving deltas: 100% (1323/1323), done.
[linuxcuba@SeguRed tmp]$ cd network-manager-l2tp/
[linuxcuba@SeguRed network-manager-l2tp]$ ./autogen.sh
ListUtil.c: loadable library and perl binaries are mismatched (got handshake key 0xdb00080, needed 0xdb80080)
My OS si up to date.

**Comment by demmm** [comment]
As linked, you will need to build the plugin yourself, including all the depends that plugin needs.  It is fully Gnome, needs a lot of Gnome depends, so won't enter the KaOS repos.
https://kaosx.us/docs/package

**Comment by LinuxCuba** [comment]
autogen.sh required automake REQUIRED_AUTOMAKE_VERSION=1.9 and KaOS automake is 1.15-6.

**Comment by demmm** [comment]
Sorry, this is for issues in KaOS apps, not  a support channel for adding packages to your install.
Closing this as won't implement for reasons explained above.

**Comment by LinuxCuba** [comment]
KaOS is of KDE Plasma Distro, in networkmanager show options for add vpn L2TP and not connect, show this error. org.freedesktop.NetworkManager.l2tp' was not installed, It is the responsibility of the maintainer of the distro that everything works correctly.

**Comment by demmm** [comment]
See what KaOS is, it is clearly marked what it is and what it is not. 
https://kaosx.us/#goals
https://kaosx.us/#repo
https://kaosx.us/docs/package and so on.

Again, clearly marked that the repos are limited to about 2000-2100, if you miss some, build yourself.

**Comment by LinuxCuba** [comment]
Yes but this error presents KaOS as it comes with its packages does not support L2TP nowhere says it, its networkmanager is incomplete, when I try to compile myself, then this error in autogen ListUtil.c: loadable library and perl binaries are mismatched Got handshake key 0xdb00080, needed 0xdb80080), how can I fix it.
