### ISSUE TITLE
syslog-ng now appears to be missing plug-in

### ISSUE THREAD

**Issue by RolandHughes** [KaOSx/apps#98]
#### Submission type

  - [ x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> syslog-ng 3.9.1.1

#### Used repositories

> KaOS primary?

#### Expected behaviour

> Should start without tossing errors.

#### Actual behaviour

> [roland@i7-desktop /]$ systemctl status syslog-ng.service
● syslog-ng.service - System Logger Daemon
   Loaded: loaded (/usr/lib/systemd/system/syslog-ng.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2017-01-29 14:46:15 CST; 25s ago
     Docs: man:syslog-ng(8)
 Main PID: 5521 (syslog-ng)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/syslog-ng.service
           └─5521 /usr/sbin/syslog-ng -F

Jan 29 14:46:15 i7-desktop systemd[1]: Starting System Logger Daemon...
Jan 29 14:46:15 i7-desktop syslog-ng[5521]: ldapdb_canonuser_plug_init() failed in sasl_canonuser_add_plugin(): invalid parameter supplied
Jan 29 14:46:15 i7-desktop syslog-ng[5521]: _sasl_plugin_load failed on sasl_canonuser_init for plugin: ldapdb
Jan 29 14:46:15 i7-desktop syslog-ng[5521]: DIGEST-MD5 common mech free
Jan 29 14:46:15 i7-desktop systemd[1]: Started System Logger Daemon.

#### Steps to reproduce the problem

> install enable start

#### System info link created by Octopi > Tools > SysInfo
https://gist.github.com/8466f6be8b70f4d755ec36d7971a2080
> …

**Comment by demmm** [comment]
KaOS is set to use systemd for logging by default (journalctl, see [Docs](https://kaosx.us/docs/#using-systemd-for-log-creation) for some examples, you will have to adjust the settings to use an alternative like syslog-ng.
Closing this issue here, since as stated before, this is NOT an Apps issue, but a core package.
