### ISSUE TITLE
Libre Office Writer does not identify all fonts loaded into system

### ISSUE THREAD

**Issue by RolandHughes** [KaOSx/apps#99]
#### Submission type

  - [x ] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> libreoffice 5.3.0.3-1

#### Used repositories

> the default ones

#### Expected behaviour

> Would offer all fonts installed on system as focuswriter does

#### Actual behaviour

> Only a subset of fonts actually appear in available font list. Fonts with Adobe and Bitstream in their names as well as many others, especially font files loaded via the system font utility

#### Steps to reproduce the problem

> Install Libre Office and FocusWriter. Open up system Font settings and view list of fonts. Open up Libre Office and look at fonts listed in combo box, many will be missing. If you try changing the font in a copied FocusWriter theme you will see the exact same list of fonts in FocusWriter that you see in the system font utility.

#### System info link created by Octopi > Tools > SysInfo

> https://gist.github.com/f56cb16ed11d09c4b5e4bf53476d3cb0

**Comment by demmm** [comment]
List the KaOS font packages you see this with.

**Comment by RolandHughes** [comment]
Unknown at package level. Been installing some other font packages trying to find a pattern. It's as if the list of installed fonts is stored on multiple files and LibreOffice only reads some of them while FocusWriter reads them all. I would guess the Adobe fonts came with the plug-in, but that is complete guess.

https://gist.github.com/df2d799537baf037698e4a654006f6ce

From a font level:
Adobe Blank
Adobe Courier
Adobe Helvetica
Adobe New Centure Schoolbook
Adobe Times
Adobe Utopia

B&H Lucida
B&H LucidaBright
B&H LucidaTypewriter

Bitstream Charter
Bitstream Terminal   -- I do have ttf-dejavu which claims to provide Bitstream Vera Fonts but these are the only 2 branded Bitstream. Typing "vera" in the search filter brings up "Average"

cursor.pcf

--  Yes, the Free fonts were installed from files via the system font utility.
--  I mention them because Free Sans  Free Mono  and Free Serif do show up in Libre Office.
--  All show up in both the font management screen and FocusWriter

Free Advant Garde
Free Bookman
Free Chancery
Free Courier
Free Helvetan
Free Schoolbook
Free Times

micro.pcf

MUTT ClearlyU Alternate Glyphs Wide
MUTT ClearlyU PUA
MUTT ClearlyU Wide

Sadly I got lost when I got down to the P's.

Octopi package search by description is useless when it comes to identifying which package provides what font. I assume that is because it is searching the content of the very limited "Info" screen instead of the full file list.

If there is a command line thing to run to back track one of these please let me know. I was shocked Octopi couldn't identify anything for MUTT. A web search turned up this:
https://www.x.org/archive/X11R6.8.0/doc/fonts3.html
http://www.xfree86.org/4.0.2/fonts3.html

**Comment by demmm** [comment]
Cannot be reproduced, reporter no longer uses KaOS.
